### ISSUE TITLE
Windows build shows cmd window

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf-compass#109]
This is a new issue related (I believe) to PR #64.
On Windows running the 1file exe brings up the main Compass window as well as a cmd window which displays logging messages.

I'm not sure what the best approach is on Windows (System Event log?) but it would be best not to show the terminal window.

**Comment by giumas** [comment]
@jreadey In such a specific case, the way to totally remove the console is by changing the `console` parameter from `True` to `False`: https://github.com/HDFGroup/hdf-compass/blob/develop/HDFCompass.1file.spec#L81

More in general, we could add an "How to release" section in the README.md with a list of required actions (e.g., set the version, update the ReadTheDocs).

**Comment by giumas** [comment]
@jreadey I have added some instructions here: https://github.com/giumas/hdf-compass/commit/0e5b081702b9e1cd6ecaf48c13c40245b4f2c2b3#diff-8035226cc524f8035c029675ed258fa0

Do we need to keep open this ticket?

**Comment by jreadey** [comment]
@giumas - thanks.  I'll do a fresh build tomorrow & close after I've verified.

**Comment by jreadey** [comment]
Verified changing the console flag works.
