### ISSUE TITLE
Weak `can_handle` approach for ASCII grid

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#122]
The current `can_handle` method for the `AsciGrid` store is weak since it essentially just checks for the file extension (.asc): https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/asc_model/model.py#L60-L69

**Comment by giumas** [comment]
This should make the approach a bit more robust: https://github.com/HDFGroup/hdf-compass/pull/123
Is this enough?

**Comment by jreadey** [comment]
I think this is good.  There's no fool-proof way to verify without reading the entire file, so this is an appropriate heuristic.
