### ISSUE TITLE
Update the "Software Using HDF5" webpage to list HDF Compass 

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#139]
Why HDF Compass is not listed here: https://www.hdfgroup.org/tools5app.html ?

**Comment by kyang2014** [comment]
Good question. I will forward the question to the HelpDesk of the HDF group.

**Comment by hyoklee** [comment]
@giumas because it is not a 3rd party app. Compass belongs to The HDF Group. 

It has a dedicated page:

https://www.hdfgroup.org/projects/compass/index.html

**Comment by kyang2014** [comment]
I had thought that way first. But HDFView is listed in that page. So I forwarded the question to the HelpDesk.

**Comment by giumas** [comment]
@kyang2014 Thank you!

@hyoklee I don't buy your explanation :) At least, the title page is misleading.. and the HDF Group Tools are listed!

Incidentally, I have attempted to download HDF Explorer, but it seems not to be free as listed in that page.

**Comment by kyang2014** [comment]
Just got the reply from the HelpDesk. This page https://www.hdfgroup.org/tools5app.html is removed.


From  our HelpDesk:

The correct pages are here:



    https://www.hdfgroup.org/products/hdf5_tools/index.html#all



I'll plan to add hdf-compass to those pages. (I'll think about how to add links to new projects that we are creating that are not released yet.)



Also, on these pages HDF Explorer is listed as commercial.

**Comment by giumas** [comment]
> I'll plan to add hdf-compass to those pages. (I'll think about how to add links to new projects that we are creating that are not released yet.)

Should we keep it open until HDFCompass will be added?

**Comment by giumas** [comment]
https://www.hdfgroup.org/tools5app.html is not more available!

**Comment by jreadey** [comment]
@giumas - for the next release I'll at least get a news blurb on the hdfgroup web site.
If you feel like writing a hdf blog about BAG support in Compass that would be most welcome and might generate some attention.

**Comment by giumas** [comment]
@jreadey I am happy to do a blog post on it. Do you have a 'template' in mind? Links to examples?

**Comment by giumas** [comment]
BTW, the information about the first release of the HDF Compass with the BAG plugin will also be published on http://www.opennavsurf.org.

**Comment by jreadey** [comment]
@giumas - Tanks for volunteering to do the blog.   My original blog post on Compass should be a reasonable example: https://hdfgroup.org/wp/2015/06/get-your-bearings-with-hdf-compass/.  You can look at some of the other blogs we've done as well.  In general, the aim is to have a light tone and not overly long.
