### ISSUE TITLE
Quit not working

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf-compass#140]
"Quit HDF Compass" is no longer exiting the application.  I see the on_exit in the debug window but the app continues to run.

**Comment by giumas** [comment]
@jreadey Mac? could you add the debug output?

**Comment by giumas** [comment]
Does it happen on script & frozen app?

**Comment by giumas** [comment]
It may be related to https://github.com/HDFGroup/hdf-compass/pull/137 to fix an issue on Windows

**Comment by jreadey** [comment]
It happens on both script and frozen apps.  On windows if I exit without opening a file, the app will close.  Otherwise the app window will close but not the container or array windows.

This is the debug output from running from script on mac:

DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:182 > Python 2.7.10 64bit on Darwin 14.5.0 (x86_64)
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:184 > numpy 1.9.3
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:185 > matplotlib 1.4.3
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:186 > wxPython 3.0.0.0
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:203 > h5py 2.5.0
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:211 > hydroffice.bag 0.2.2
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:214 > lxml 3.4.4 (libxml 2.9.2, libxslt 1.1.28)
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:227 > pydap 3.1.1 (protocol 2.15)
DEBUG   hdf_compass.compass_viewer.frame.__init__:69 > new frame -> open frames: 1
DEBUG   hdf_compass.hdf5rest_model.model.can_handle:138 > hdf5rest can_handle: file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5
DEBUG   hdf_compass.hdf5rest_model.model.get_json:47 > GET: file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5
DEBUG   hdf_compass.hdf5rest_model.model.can_handle:149 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no
INFO    pydap.request:39 > Opening file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5.dds
DEBUG   hdf_compass.opendap_model.model.can_handle:54 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no
DEBUG   hdf_compass.asc_model.model.can_handle:66 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no, missing .asc extension
DEBUG   hdf_compass.bag_model.model.can_handle:77 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no, not a BAG
DEBUG   hdf_compass.hdf5_model.model.can_handle:79 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? yes
DEBUG   hdf_compass.array_model.model.can_handle:85 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no
DEBUG   hdf_compass.filesystem_model.model.can_handle:63 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no
DEBUG   hdf_compass.hdf5_model.model.can_handle:79 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? yes
DEBUG   hdf_compass.hdf5rest_model.model.can_handle:138 > hdf5rest can_handle: file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5
DEBUG   hdf_compass.hdf5rest_model.model.get_json:47 > GET: file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5
DEBUG   hdf_compass.hdf5rest_model.model.can_handle:149 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no
INFO    pydap.request:39 > Opening file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5.dds
DEBUG   hdf_compass.opendap_model.model.can_handle:54 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no
DEBUG   hdf_compass.asc_model.model.can_handle:66 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no, missing .asc extension
DEBUG   hdf_compass.bag_model.model.can_handle:77 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no, not a BAG
DEBUG   hdf_compass.hdf5_model.model.can_handle:79 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? yes
DEBUG   hdf_compass.array_model.model.can_handle:85 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no
DEBUG   hdf_compass.filesystem_model.model.can_handle:63 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? no
DEBUG   hdf_compass.hdf5_model.model.can_handle:79 > able to handle file:///Users/jreadey/Compass/hdf-compass/data/hdf5/tall.h5? yes
DEBUG   hdf_compass.compass_viewer.viewer.open_node:118 > Top-level open called for <hdf_compass.hdf5_model.model.HDF5Group object at 0x10e47df10>
DEBUG   hdf_compass.compass_viewer.frame.__init__:69 > new frame -> open frames: 2
DEBUG   hdf_compass.compass_viewer.frame.on_exit:131 > exit frame -> open frames: 1

**Comment by giumas** [comment]
I understood. To be honest, I think to this as a feature.. rather than a bug. I can fix it very quickly if you don't like this behavior. So, you want that, only for the `InitFrame`, when it is closed, all the other frames are closed.

>  DEBUG hdf_compass.compass_viewer.frame.on_exit:131 > exit frame -> open frames: 1

The 1 is because the app is tracking the open frames, and it only exit when they are all closed.

This PR should have the behavior that you were asking about: https://github.com/HDFGroup/hdf-compass/pull/141

**Comment by giumas** [comment]
The app behavior should be now more 'normalized'. Closed.
