### ISSUE TITLE
Get out of the dead/relic branches?

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#149]
On the upstream repository there might be a couple of relic / dead branches. Can we delete them?

* shell: https://github.com/HDFGroup/hdf-compass/tree/shell  (@jreadey) 
* openas_menu: https://github.com/HDFGroup/hdf-compass/tree/openas_menu (@andrewcollette)

**Comment by andrewcollette** [comment]
openas_menu, as far as I recall, is not useful for anything anymore.

**Comment by jreadey** [comment]
I'd keep the shell branch - I'd like to get back to it sometime.

**Comment by giumas** [comment]
``openas_menu`` branch removed

what is the idea behind the ``shell`` branch?

**Comment by jreadey** [comment]
The idea of a shell branch is to enable a sort of command line version of compass.  Something like:
> open mydata.h5
OK
> ls /g1/g1.1
dset1.1
dset1.2
> cd /g1/g1.1
OK
> plot dset1.1
