### ISSUE TITLE
'module' object has no attribute 'ST_ELLIPSIZE_MIDDLE'

### ISSUE THREAD

**Issue by NAThompson** [HDFGroup/hdf-compass#151]
After installation of dependencies, I attempted to open an hdf5 file and got the following error:

    File "/home/nthompson/hdf-compass/compass_viewer/info.py", line 41, in __init__
    self.nametext = wx.StaticText(self, style=wx.ALIGN_LEFT|wx.ST_ELLIPSIZE_MIDDLE, size=(PANEL_WIDTH-40,30))
    AttributeError: 'module' object has no attribute 'ST_ELLIPSIZE_MIDDLE'

I imagine this occurs due to installation of an incompatible version of wxPython, but I'm not sure. It would be nice if we had an `apt-gets.txt` and a `requirements.txt` with explicitly pinned dependencies so we could run

    hdf-compass$ xargs sudo apt-get install -y < apt-gets.txt
    hdf-compass$ virtualenv .
    hdf-compass$ pip install -r requirements.txt
    hdf-compass$ python HDFCompass.py

and have a clean install. I would be happy to submit this pull request myself, but the `requirements.txt` would most likely be incorrect.

**Comment by giumas** [comment]
Did you read the project setup.py? It should be enough to modify the wxPython row in the dependencies.. then pip install .

**Comment by giumas** [comment]
@jreadey In the meantime that we wait for a stable wxPython release, we might want to check the version of wxPython at the startup, and in case exiting with a clear message like "This wxPython release (3.0.2) is not supported, please run pip install setup.py in a virtual env with wxPython <= 3.0.0".

@NAThompson FYI, I have successfully tested it using the current wxPython hosted on anaconda.org (3.0.0).

**Comment by jreadey** [comment]
@giumas - how about the change to the README I just pushed?  Given the sensitivity to the wxPython release, recommending that only 3.0.0 be used for development.

**Comment by giumas** [comment]
I cannot find it.. the last listed commit to the 'develop' branch is 8-day old

**Comment by jreadey** [comment]
Sorry, I was on the wrong branch.  Take a look now.

**Comment by giumas** [comment]
It should be safe.. ``StaticText`` is listed here as one of the class which needa to be changed to a new syntax in Phoenix: http://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html#classic-vs-phoenix

**Comment by giumas** [comment]
@NAThompson Did you manage to run the application without the error? I am testing with WxPython on Windows without error. Which version of WxPython were you running?

**Comment by giumas** [comment]
Closed for lack of user feedback!
