### ISSUE TITLE
HDFCompass crashes on OS X 10.11 on startup

### ISSUE THREAD

**Issue by svniemeijer** [HDFGroup/hdf-compass#152]
When trying to start the application it crashes with the attached crash log
[crashlog.txt](https://github.com/HDFGroup/hdf-compass/files/35755/crashlog.txt)

**Comment by giumas** [comment]
Are you running version 0.5.0?

**Comment by svniemeijer** [comment]
0.5.1

**Comment by giumas** [comment]
Try the develop version: https://github.com/HDFGroup/hdf-compass/issues/79#issuecomment-150876752

**Comment by svniemeijer** [comment]
That one works. Thanks.
You might want to get the main page updated to point to those delta releases:
https://www.hdfgroup.org/projects/compass/

**Comment by jreadey** [comment]
@svniemeijer - The delta releases are not extensively tested, so it's probably best for the broader public not be to be using them.  The plan is to get to the 0.6 release target (https://github.com/HDFGroup/hdf-compass/issues/79), spend some time testing, and then update the hdfgroup project page.

**Comment by svniemeijer** [comment]
Well, in the mean time other users might try the official OS X version and have it fail as well. Right now it looks like it is better for the broader (OS X using) public to use the 0.6 release target then it is using the 0.5.x version.
