### ISSUE TITLE
ADIOS Plugin

### ISSUE THREAD

**Issue by ax3l** [HDFGroup/hdf-compass#155]
Hi and thank you for the great project! :sparkles: 

I was wondering how much work would be required to add an [ADIOS](https://www.olcf.ornl.gov/center-projects/adios/) ([GitHub Repo](https://github.com/ornladios/ADIOS), [Numpy Wrapper Module](https://github.com/ornladios/ADIOS/tree/master/wrappers/numpy)) plugin to HDF Compass, since that would be a fantastic way to explore `.bp` files, too!

Does the support really just need `model` file and some tests as with [opendap](https://github.com/HDFGroup/hdf-compass/tree/develop/hdf_compass/opendap_model)/[filesystem](https://github.com/HDFGroup/hdf-compass/tree/develop/hdf_compass/filesystem_model)/[hdf5](https://github.com/HDFGroup/hdf-compass/tree/develop/hdf_compass/hdf5_model)/...? What are the general minimum/optimal interfaces that need to be implemented (looks like all are optional but the more one implements the more one gets, is that correct)?

I found [hdf_compass/compass_model/model.py](https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/compass_model/model.py) which seems to define:
- [compass_model.Store](https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/compass_model/model.py#L96-L99): a file object
- [compass_model.Container](https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/compass_model/model.py#L309-L314): a group / directory (?) (adios currently does not know groups due to a flat index table for both attributes & variables but those could be parsed from `/their/individually/named/path` and the adios numpy wrapper might already add that abstraction in the future)
- [compass_model.Array](https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/compass_model/model.py#L364-L369): a data set (adios naming: `variable`)
- [compass_model.KeyValue](https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/compass_model/model.py#L340-L347): attributes on groups and arrays (data sets/variables)?
- [compass_model.Text](https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/compass_model/model.py#L425-L426): _I do not understand that one_ but I guess it handles char 1D char arrays (and [arrays of strings](https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/hdf5_model/model.py#L284-L285)?) in a useful way for displaying them (?)
- [compass_model.Image](https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/compass_model/model.py#L395-L398): I guess that is for HDF5 since Images are kind of special data sets in HDF5 :)

I could not find a "how to build a new plugin/backend/model" page or wiki entry, please excuse me if I have overseen one :)

I guess travis-ci and `appveyor` integration would be used to test the plugin's tests, too.
## 

@yyalli you might be interested in that, too :)

**Comment by jreadey** [comment]
Thanks for your interest in the project!

Sorry we don't have a "how to write a plugin" guide yet, but it's really pretty simple.
Look at one of the simpler plugins (like asc_model) and you should get a good idea of the essentials.

You can do the model overrides just for the components that make sense for your format.  Say: Store/Array/KeyValue.  If the way these components are displayed visually work for you, that's all you need to do.  Also - you'll need to put some code in the load_plugins method in viewer.py.

The text component was developed for the BAG plugin to have a nice way to display text and xml blobs.

If you submit a PR request for an ADIOS plugin, I'd be happy to review.  Also we can keep this issue open for an questions that come up.

**Comment by ax3l** [comment]
dear @jreadey, thank you for the quick response!

we will start working on it today and implement it as far we can get, thanks a lot for offering help with a review :sparkles: we will probably start immediately from the `h5py` plugin.

Our development branch will be https://github.com/ComputationalRadiationPhysics/hdf-compass/tree/topic-adios and we will start from your repo's `develop` branch.

**Comment by ax3l** [comment]
a PR is now opened in #173

**Comment by giumas** [comment]
Based on my understanding of the ADIOS building issues (in particular, on Windows: https://github.com/ornladios/ADIOS/issues/77) AND given that the plugin does not crash HDF Compass when the ADIOS package is missing, my proposal is:
- to merge the PR  https://github.com/HDFGroup/hdf-compass/pull/173
- to leave the ADIOS plugin out of the plugins in the frozen applications that the HDF Group officially releases (until it is demonstrated how to smoothly build with it also on Mac and Win).

I understand that this solution is not perfect, but at least it makes things moving forward.

**Comment by jreadey** [comment]
@ax3l how do you feel about this?  I'd be fine with doing the merge, but have your organization provide frozen binaries that include the ADIOS plugin.  The HDF Group build would continue to provide binaries that do not include ADIOS (until we have a better grip on the install and compatibility issues).

**Comment by ax3l** [comment]
That sounds good to me, but I would like to automate distribution anyway.

A few updates:
- the install on OSX and Linux of ADIOS is now minimalized and works without MPI (PR #173 updated)
- packing via `pyinstaller` (dev) on OSX:
  - is your `py2app` install broken?
  - `PyQt4` seems to make problems on travis with `pyinstaller`
  - https://travis-ci.org/ComputationalRadiationPhysics/hdf-compass/builds/147733989

Ideas:
- to try Windows installs you could activate your `appveyor` hook again
- I saw in the `.travis.yml` that someone already activated uploading artifacts (final binaries) to AWS, maybe this could be the cleanest way to automatically generate and distribute?
- one could think about generating conda packages (for HDF Compass itself and for ADIOS https://github.com/ornladios/ADIOS/issues/81)
- I think we can start shipping ADIOS with HDFCompass in the time frame of the next stable ADIOS release `1.10.0` and the next stable `pyinstaller` release (new hook! `>3.2`) so we have stable versions to point to

**Comment by jreadey** [comment]
The newly merged develop branch is failing the Travis build: https://travis-ci.org/HDFGroup/hdf-compass/jobs/147795057.

@ax3l - any idea what is up with that?  Travis build was working on the PR.

**Comment by ax3l** [comment]
ah it's the upstream cleanup I just proposed. I did not expect this to have a side effect.
  https://github.com/ornladios/ADIOS/pull/76

will fix this asap (and we are currently adding CI to adios itself, too.)

**Comment by ax3l** [comment]
fix provided. sorry, that was a bit awkward... (the cache for the ADIOS c library in travis was not yet build; PRs and branches have independent caches in travis.) can you please just restart the test in travis as soon as https://github.com/ornladios/ADIOS/pull/82 is merged?

**Comment by ax3l** [comment]
merged! :)

Just go to
- https://travis-ci.org/HDFGroup/hdf-compass/
- log in
- on the right upper side you can "restart" the failed test

again: sorry, that was my very bad timing.

**Comment by giumas** [comment]
> is your py2app install broken?

In the past, `py2app` was the official way to freeze the app on Mac. I have worked to use `pyinstaller` also on Mac. In my opinion, the `py2app` script might now be deleted. @jreadey , do you thoughts on it?

**Comment by ax3l** [comment]
sounds great! did you have problems as I [reported above](https://github.com/HDFGroup/hdf-compass/issues/155#issuecomment-235557366) with PyQt4 on OSX? I saw you [excluded PyQt4](https://github.com/HDFGroup/hdf-compass/blob/208f06921b6b2b11932e9f2d70acd48c857cb7b9/setup.py2app.py#L54) in the `py2app` scripts. I reported this upstream [here](https://github.com/pyinstaller/pyinstaller/pull/1389), too.

**Comment by giumas** [comment]
From my understanding, PyInstaller does not officially support the miniconda/anaconda tweaks. It might be related.

When I freeze the application, I usually prefer to use a clean environment with just what is required.

**Comment by jreadey** [comment]
I'm good with just pyinstaller.  I deleted py2app on develop.

**Comment by jychoi-hpc** [comment]
Hi. I am testing with ADIOS plugin on OSX. Then, is the following command (as indicated in README) is valid for OSX?
$ pyinstaller --clean -y HDFCompass.1file.spec
$ pyinstaller --clean -y HDFCompass.1folder.spec

I just tried but got an error related with hydroffice.bag. So, I tried to install but again got an error while installing hydroffice.bag on OSX.

**Comment by ax3l** [comment]
@yyalli yes that's a common problem and a hard to install dependency. you can just disable it for the test [like this](https://github.com/HDFGroup/hdf-compass/pull/173#issuecomment-231760713).

Also, in the same file (`HDFCompass.1[file|folder].spec`) you will need to apply [this patch](https://github.com/HDFGroup/hdf-compass/pull/173#issuecomment-231884489) since my pyinstaller hook for adios is already merged but not yet released: https://github.com/pyinstaller/pyinstaller/pull/2096

All in all the diff is:

``` diff
diff --git a/HDFCompass.1file.spec b/HDFCompass.1file.spec
index 0743d5f..1ff3ba7 100644
--- a/HDFCompass.1file.spec
+++ b/HDFCompass.1file.spec
@@ -50,7 +50,7 @@ def collect_pkg_data(package, include_py_files=False, subdir=None):
     return data_toc

 pkg_data_hdf_compass = collect_pkg_data('hdf_compass')
-pkg_data_bag = collect_pkg_data('hydroffice.bag')
+#pkg_data_bag = collect_pkg_data('hydroffice.bag')
 cartopy_aux = []
 try:  # for GeoArray we use cartopy that can be challenging to freeze on OSX to dependencies (i.e. geos)
     import cartopy.crs as ccrs
@@ -71,7 +71,8 @@ app_name = 'HDFCompass_' + version
 a = Analysis(['HDFCompass.py'],
              pathex=[],
              hiddenimports=['scipy.linalg.cython_blas', 'scipy.linalg.cython_lapack',
-               'scipy.linalg', 'scipy.integrate'],  # for cartopy
+                'scipy.linalg', 'scipy.integrate',  # for cartopy
+                'adios._hl.selections'], # pyinstaller <=3.2 has no ADIOS hook
              excludes=["PySide"],  # exclude libraries from being bundled (in case that are installed)
              hookspath=None,
              runtime_hooks=None)
@@ -83,7 +84,7 @@ exe = EXE(pyz,
           a.zipfiles,
           a.datas,
           pkg_data_hdf_compass,
-          pkg_data_bag,
+#          pkg_data_bag,
           cartopy_aux,
           name=app_name,
           debug=True,
```

**Comment by ax3l** [comment]
wuhu, solved travis OSX packing! just add `excludes=["PySide", "PyQt4"],` in the excludes of `HDFCompass.1[file|folder].spec`.

Will try on Yosemite in a few minutes and upload a binary for testing.
Here is an all-successful travis build + packing: https://travis-ci.org/ComputationalRadiationPhysics/hdf-compass/builds/147847831

**Comment by ax3l** [comment]
Ok, that's how far I got:
- Linux & OSX packing (latter on Yosemite) works
- both 64bit
- adios install is straight forward on both operating systems (git, autotools, gcc/Xcode; --without-mpi)
- for the specific package I uploaded, OSX general plotting of a data set crashes in packed mode (plugin-independent problem; works outside the package - probably due to the weird `PyQt4` [install from conda](https://github.com/pyinstaller/pyinstaller/pull/1389#issuecomment-235572323) that I excluded in packing)

Downloads:
- https://owncloud.hzdr.de/index.php/s/6CSZ5mzxrlUF9d1
- password: compass

**Comment by giumas** [comment]
> I just tried but got an error related with hydroffice.bag. So, I tried to install but again got an error while installing hydroffice.bag on OSX.

@yyalli If you don't report the kind of error, it is hard to help!

> @yyalli yes that's a common problem and a hard to install dependency. 

@ax3l You broke my heart with this sentence! I am the `hydroffice.bag` maintainer (incidentally, the library is born as a side project of the BAG plugin), so I can testify that you did not report any issue on the `hydroffice.bag` project issue tracker: https://bitbucket.org/ccomjhc/hyo_bag/issues?status=new&status=open

Furthermore, the library is in pure python, so it does not require any compilation step. I can thus assume that you have troubles with one of the 2 dependencies: `gdal` and `lxml` that are both quite popular. Did you try to install them using `conda`?

Finally, there are 2 wiki pages that describe the environment that we used in the last release:
- https://github.com/HDFGroup/hdf-compass/wiki/Notes-on-freezing-with-Mac-OS-X
- https://github.com/HDFGroup/hdf-compass/wiki/Notes-on-freezing-with-Windows

**Comment by giumas** [comment]
> adios install is straight forward on both operating systems (git, autotools, gcc/Xcode; --without-mpi)

My definition of straight forward install would be `pip install adios` or `conda install adios`.

**Comment by giumas** [comment]
> for the specific package I uploaded, OSX general plotting of a data set crashes in packed mode (plugin-independent problem; works outside the package 

@ax3l : Can you run the frozen application from a shell and then post the error trace? 

> - probably due to the weird PyQt4 install from conda that I excluded in packing)

I  have doubts on that.

**Comment by ax3l** [comment]
> @ax3l You broke my heart with this sentence! I am the hydroffice.bag maintainer (incidentally, the library is born as a side project of the BAG plugin), so I can testify that you did not report any issue on the hydroffice.bag project issue tracker: https://bitbucket.org/ccomjhc/hyo_bag/issues?status=new&status=open

ahhh, no hard feelings :)
I had problems installing it an linux and it seemed it did not optionally "vanish" from the freezing as it should in compass, so I skipped it for going on. I will try this again after my travels (will be two weeks off) and report in the according issue trackers, but it's off-topic for this thread.

@yyalli if you have troubles, can you split the hydrooffice questions in a separate thread on it's [bitbucket issue tracker](https://bitbucket.org/ccomjhc/hyo_bag/issues) (Github: [issues](https://github.com/hydroffice/hyo_bag/issues))  or apply [my patch as a work-around](https://github.com/HDFGroup/hdf-compass/issues/155#issuecomment-235686609) for the adios freezing, please? :)

@giumas btw, I get an "access denied" when visiting the bitbucket link. Are you sure `issues` are enabled in https://bitbucket.org/ccomjhc/hyo_bag ? Otherwise, @yyalli here is the github mirror of the project: https://github.com/hydroffice/hyo_bag

> >  adios install is straight forward on both operating systems (git, autotools, gcc/Xcode; --without-mpi)
> 
> My definition of straight forward install would be pip install adios or conda install adios.

mine, too - and we are working on that https://github.com/ornladios/ADIOS/issues/81
nevertheless, running

``` bash
# c lib
./autogen.sh # only for pre-releases from git
CFLAGS="-fPIC -g" ./configure --without-mpi --enable-static --disable-shared --prefix=/usr
make && sudo make install

# numpy wrapper
cd wrappers/numpy
python setup.py install --user
```

is the classic rule of three     and the classic python setup. Let us add those to the wiki, too (I can't edit it; on OSX install to `/usr/local` instead). Adios is also in aur and debian/ubuntu mainline repos, so one can even replace the c lib compile with a package install (when `1.10.0` is released).

> @ax3l : Can you run the frozen application from a shell and then post the error trace?

I tried to, but yesterday at 11:45pm I forgot the OSX cmd line command to start an app is called `open -a ...` (OSX noob that I am). I [uploaded the binary](https://github.com/HDFGroup/hdf-compass/issues/155#issuecomment-235728927), in case someone has a mac on hands.

**Comment by giumas** [comment]
@ax3l  can we close this ticket?

**Comment by ax3l** [comment]
Sure, ping me if you ever experience problems with it.

**Comment by ax3l** [comment]
Sure, ping me if you ever experience problems with it.

**Comment by ax3l** [comment]
Sure, ping me if you ever experience problems with it.

**Comment by ax3l** [comment]
Sure, ping me if you ever experience problems with it.
