### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by ghisvail** [HDFGroup/hdf-compass#160]
I am opening a separate meta issue for all my questions / remarks / requests, whilst dealing with the packaging work on Debian (like #159).

**Comment by ghisvail** [comment]
Amongst the list of dependencies for hdf-compass:
```python
setup_args['install_requires'] =\
    [
        "numpy",
        "matplotlib>=1.5",
        "cartopy[plotting]",
        "h5py",
        "wxPython==3.0.2",
        "hydroffice.bag>=0.2.10",
        "pydap",
        "requests"
    ]
```
Debian is currently missing `cartopy`, `hydroffice.bag` and `pydap`. Cartopy is supposedly being worked on, hydroffice.bag is in my backlog and pydap is not available. We have `dap`, but I am assuming it is outdated and superseded by pydap. I wonder which of these dependencies are trully necessary for running `hdf-compass` and which of those could be moved to `extra_requires`.

**Comment by giumas** [comment]
Does it help?

```python
    setup_args['install_requires'] =\
    [
        "numpy",
        "matplotlib>=1.5",
        "h5py",
        "wxPython==3.0.2",
        "requests"
    ]
    setup_args['extras_require'] =\
    {
        "GeoNodes": ["cartopy[plotting]", ],  # required for visualization of GeoArray and GeoSurface nodes
        "BAG": ["hydroffice.bag>=0.2.10", ],  # required by BAG plugin
        "OpenDAP": ["pydap", ],  # required by OpenDAP plugin
    }
```

**Comment by ghisvail** [comment]
It does, yes. So that means we do have all the essentials in place in Debian.

**Comment by giumas** [comment]
As `hydroffice.bag` maintainer, I hope that you can also add the BAG plugin.. Incidentally, this plugin is currently the only one that takes advantage of the the `GeoNodes` dependency to geo-visualize the data.

**Comment by ghisvail** [comment]
so it would require `cartopy` too?

**Comment by giumas** [comment]
Nope! It reverts to visualize the data as simple Array nodes if `cartopy` is missing.

**Comment by ghisvail** [comment]
Could you guys provide a scalable and / or PNG version of the application icon? Right now, I am running imagemagick during the package build to generate a [freedesktop compliant](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) .png from the .ico but a .svg would make it look better, regardless of the screen resolution or application launcher.

**Comment by giumas** [comment]
Does it work? https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/compass_viewer/icons/favicon_48.png

**Comment by ghisvail** [comment]
I now have a working package for `0.6.0b4`. You should consider merging #162 which would benefit packaging efforts for other distributions. In addition, you guys might want to have a look at the [AppStream standard](https://www.freedesktop.org/wiki/Distributions/AppStream/) for better discovery in software stores.

**Comment by giumas** [comment]
Great! new tag: https://github.com/HDFGroup/hdf-compass/releases/tag/v0.6.0b5

**Comment by ghisvail** [comment]
Perfect. The packaging is ready on my end. I'll should perhaps wait for the final `v0.6.0` tag before doing the submission?

**Comment by giumas** [comment]
@ghisvail Great! 

For the release decision, we need somebody from the HDF Group: @jreadey ? @hyoklee ? @ajelenak-thg ? and I would also invoke the opinion of @andrewcollette

**Comment by giumas** [comment]
@ghisvail can I hope that the packaging is with the BAG plugin?

**Comment by jreadey** [comment]
I'd like to have frozen binaries built and tested for Mac & Windows before releasing v0.6.0.

**Comment by giumas** [comment]
Does it mean that these binaries do not work? https://github.com/HDFGroup/hdf-compass/releases/tag/v0.6.0b3 Or that is required that binaries are built on HDF Group's machines? 

Incidentally, I am also a bit concerned about the lack of recent developer time put on the project. Is this a project that the HDF Group wants to really push for?

**Comment by jreadey** [comment]
The binaries don't work on my Mountain Lion System.  And I would say the binaries need to be built on HDF Group's machine if we are to be the one's to distribute them.

I think at this point it makes sense to move the minimal OS X version to Yosemite (10.10).  For example I notice that Chrome is no longer supported on 10.8 and in general it's hard to get the binary build dependencies on 10.8.

Sorry for the lack of time the HDF Group has been able to put in to this project recently.  Compass is a great tool, but it has to take a back seat to projects that customers are paying us for.  I will spend some time this week to get the build setup for v0.6.0.

**Comment by giumas** [comment]
> The binaries don't work on my Mountain Lion System. 
What is the error? I would like to understand better what is the general issue. Do we really need to have a frozen app for each supported OS X?

>  I will spend some time this week to get the build setup for v0.6.0.
This is great!

**Comment by ghisvail** [comment]
> I will spend some time this week to get the build setup for v0.6.0.

Awesome. Then, what I can do is submit the packaging of v0.6.0b5 for review (which always take some time to complete) and update to v0.6.0 once it is released. Is that ok?

**Comment by jreadey** [comment]
Re: the runtime error, it was similar to this: http://stackoverflow.com/questions/25926495/symbol-not-found-sincos-stret.

In general, binaries built on one version of OS X won't run on previous versions.  So I'm trying to setup a build machine with a OS X release recent enough to be able to build Compass w/ the various plugins and old enough that most Mac users will have it or a newer release.  I wasn't able to find a download for 10.10 on the Mac developer site: https://developer.apple.com/osx/download/.  Does anyone know if they are still keeping a Yosemite DMG around?

**Comment by giumas** [comment]
> I wasn't able to find a download for 10.10 on the Mac developer site: https://developer.apple.com/osx/download/. Does anyone know if they are still keeping a Yosemite DMG around?

I am afraid that Yosemite was already removed.. [Bad guys!!](http://www.ginnymcqueen.com/wp-content/uploads/2014/09/apple.jpg)

BTW, if you downloaded it in the past, shouldn't it be in your purchases in the App Store?

**Comment by jreadey** [comment]
Good idea! - I do have it on my App Store/Purchased tab.  I'll give it a go.

**Comment by jreadey** [comment]
@giumas - I was able to follow your wiki and create a dmg on OS X 10.10!   Since this is 10.10, I didn't need to deal with the WxPython work-around.

The binary is here: s3://hdfgroup.download/HDFCompass/0.6.0b5/HDFCompass.dmg, try it out and let me know if you see any issues.

Next, I'll try the same on Windows 7.

**Comment by giumas** [comment]
Do you mean: [https://s3.amazonaws.com/hdfgroup.download/HDFCompass/0.6.0b5/HDFCompass.dmg](https://s3.amazonaws.com/hdfgroup.download/HDFCompass/0.6.0b5/HDFCompass.dmg )?

**Comment by giumas** [comment]
It works on my Yosemite machine:

![vmplayer_2016-05-04_08-46-12](https://cloud.githubusercontent.com/assets/2849257/15014577/d200fa5a-11d4-11e6-966d-645fc854e351.png)

**Comment by jreadey** [comment]
Great!  Yes I meant to say https://...

**Comment by giumas** [comment]
@jreadey I have found much easier the building on Windows. Are you hitting issues?

**Comment by jreadey** [comment]
@giumas - I didn't get to it today.  Some questions for windows: 
* Do I need Visual C++ installed?
* What's the windows equivalent for installing, say, ``brew install geos``?

**Comment by giumas** [comment]
I have done all smoothly with Anaconda.. and no need of Visual Studio

**Comment by jreadey** [comment]
@giumas - I'd used just pip previously, but I'm setting up a new system with Win 7 and Anaconda now.
I don't see a anaconda package for libxml2 on windows - what did you do for that?

**Comment by giumas** [comment]
I did `pip install lxml` since there is wheel for `lxml` in PyPi: https://pypi.python.org/pypi/lxml/3.6.0

**Comment by jreadey** [comment]
Ok, got it - is there any need to set the headers as described in the wiki?

**Comment by giumas** [comment]
Actually, also `conda install xml` works..
Nope, the main idea of the Python wheel is to avoid any compilation on the user machine.

**Comment by jreadey** [comment]
Speaking of avoiding compilation, ``pip install hydroffice.bag`` gives an error: ``Microsoft Visual C++ 9.0 is required``.  Is there a wheel for hydroffice?

**Comment by giumas** [comment]
`hydroffice.bag` is a pure python library, so it cannot require compilation. Most likely, it is one of the dependencies.. which one? Can you post the error?

**Comment by giumas** [comment]
`conda install gdal=1.11` ?

**Comment by giumas** [comment]
If you already have installed all the `hydroffice.bag` dependencies, but `pip` still try to compile some dependencies.. you can force to avoid to build the depending library by running `pip install --no-deps hydroffice.bag`

**Comment by giumas** [comment]
Or you can download and install a wheel for GDAL from here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal

**Comment by jreadey** [comment]
Right, actually the error line before this was: "Failed build wheel for gdal" - turns out I had forgotten to install gdal.  Now hydroffice in installed.

Did you do a conda install for wxPython? I did and got version 3.0.0 instead of 3.0.2.

**Comment by giumas** [comment]
This is what I was talking here: https://github.com/HDFGroup/hdf-compass/pull/159#discussion_r61321097

I have used the official release:  http://www.wxpython.org/download.php

**Comment by jreadey** [comment]
Ok, python HDFCompass.py runs fine with the wxpython download, and I'm able to build the exe.  Running the exe gives the following error.  Any ideas?

```
$ ./HDFCompass_0.6.0b5.exe
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "c:\users\john\appdata\local\temp\pip-build-vlhpky\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\setuptools-20.7.0-py2.7.egg\pkg_resources\__init__.py", line 68, in <module>
  File "site-packages\setuptools-20.7.0-py2.7.egg\pkg_resources\extern\__init__.py", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\john\hdf-compass\dist\HDFCompass\HDFCompass_0.6.0b5.exe
LOADER: homepath is C:\Users\john\hdf-compass\dist\HDFCompass
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Users\john\hdf-compass\dist\HDFCompass\HDFCompass_0.6.0b5.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(C:\Users\john\hdf-compass\dist\HDFCompass)
LOADER: Already in the child - running user's code.
LOADER: Python library: C:\Users\john\hdf-compass\dist\HDFCompass\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Users\john\HDF-CO~1\dist\HDFCOM~1
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\john\hdf-compass\dist\HDFCompass
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_qt4plugins.py
LOADER: Running pyi_rth_pkgres.py
Failed to execute script pyi_rth_pkgres
LOADER: OK.
LOADER: Cleaning up Python interpreter.
```

**Comment by jreadey** [comment]
Actually, back to when I did pip install I get this error:
```
[Anaconda2] C:\Users\john\hdf-compass>pip install -e .
Obtaining file:///C:/Users/john/hdf-compass
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\users\john
\appdata\local\continuum\anaconda2\lib\site-packages (from hdf-compass==0.6.0b5)

Requirement already satisfied (use --upgrade to upgrade): matplotlib>=1.5 in c:\
users\john\appdata\local\continuum\anaconda2\lib\site-packages (from hdf-compass
==0.6.0b5)
Requirement already satisfied (use --upgrade to upgrade): h5py in c:\users\john\
appdata\local\continuum\anaconda2\lib\site-packages (from hdf-compass==0.6.0b5)
Collecting wxPython==3.0.2 (from hdf-compass==0.6.0b5)
  Could not find a version that satisfies the requirement wxPython==3.0.2 (from
hdf-compass==0.6.0b5) (from versions: )
No matching distribution found for wxPython==3.0.2 (from hdf-compass==0.6.0b5)
```
Strange, bacause if I do:
```
   $ python
   import wx
   print wx.version()
```
I get: 3.0.2 msw (classic)

**Comment by giumas** [comment]
This applies: https://github.com/HDFGroup/hdf-compass/wiki/Notes-on-freezing-with-Mac-OS-X#hdf-compass-freezing
On the `pyinstaller` project, they state that the problem with `setuptools` is solved, but on my machine only works if I downgrade it

**Comment by giumas** [comment]
@jreadey since we do the freezing once in a while, it might be useful to do something like the OS X wiki for Windows.. to write down all these tweaks

**Comment by giumas** [comment]
what do you get when you execute: `pip list` for `wxPython`? There might be inconsistencies in the naming

**Comment by jreadey** [comment]
wxPython doesn't show up.  Pip doesn't know about it unless I install the package with pip or conda?

**Comment by giumas** [comment]
I think so

**Comment by jreadey** [comment]
After reverting setuptools to 19.2, I'm able to build and run the .exe.
But attempting to plot anything gives an error: "Cannot load mkl_mc.dll or mkl_def.dll".  Has anyone seen this on Windows?  

There a suggestion to fix this by explicitly loading the dlls: https://github.com/pyinstaller/pyinstaller/issues/844, but I'm wondering if I'm the only one running into this and why.

**Comment by giumas** [comment]
I had the same issue.. It is function of the numpy version. There are various solutions: the easiest/quickest is to just copy this dll in the 1-folder application or to tell PyInstaller to include the dlls in the 1-file application

**Comment by giumas** [comment]
You can resolve the issue by identifying where that dlls are in your machine, then: 

     a.binaries + [('my_lib.dll', 'path/to/dll', 'BINARY')]

**Comment by ghisvail** [comment]
Are there any unit tests for the hdf_compass public module?

**Comment by giumas** [comment]
@kyang2014 can you answer this question? What is the current status of your efforts?

**Comment by jreadey** [comment]
@giumas - With adding the dlls, running the resultant exe gives the following error.  Have you seen this?

```
[Anaconda2] C:\Users\john\hdf-compass\dist\HDFCompass>HDFCompass_0.6.0b5.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\john\hdf-compass\dist\HDFCompass\HDFCompass_0.6.0
b5.exe
LOADER: homepath is C:\Users\john\hdf-compass\dist\HDFCompass
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Users\john\hdf-compass\dist\HDFCompass\HDFCompass_0.6.
0b5.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(C:\Users\john\hdf-compass\dist\HDFCompass)
LOADER: Already in the child - running user's code.
LOADER: Python library: C:\Users\john\hdf-compass\dist\HDFCompass\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Users\john\HDF-CO~1\dist\HDFCOM~1
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\john\hdf-compass\dist\HDFCompass
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_qt4plugins.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running pyi_rth_win32comgenpy.py
LOADER: Running pyi_rth__tkinter.py
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth__tkinter.py", line 28,
in <module>
IOError: Tcl data directory "C:\Users\john\HDF-CO~1\dist\HDFCOM~1\tcl" not found
.
Failed to execute script pyi_rth__tkinter
LOADER: OK.
LOADER: Cleaning up Python interpreter.
```

**Comment by giumas** [comment]
This is new! And weird since we don't use `tkinter`.. Which version of PyInstaller are you using? Try to exclude 'tkinter'! https://github.com/pyinstaller/pyinstaller/issues/1584

**Comment by jreadey** [comment]
Ok, I'll give that a try.   It will need to wait till Friday though, I'm traveling through Thursday.

**Comment by jreadey** [comment]
Ok - the Windows exe is available here: https://s3.amazonaws.com/hdfgroup.download/HDFCompass/0.6.0b5/HDFCompass.exe. 
From my limited testing it is working with HDF5 files and BAG.  

Let's bang on this (and the OS X build) this week, an if no show stoppers update the version to 0.6 and do an "official" release.

**Comment by giumas** [comment]
Great! 

Two things:

* you might announce it on this thread: https://github.com/HDFGroup/hdf-compass/issues/79
* what is the issue with OpenDap? 
![2016-05-16_08-27-44](https://cloud.githubusercontent.com/assets/2849257/15289479/70e94d9c-1b40-11e6-9194-af5e0d44c7bf.png)

**Comment by jreadey** [comment]
I've updated #79.

Looks like I forgot to do a pip install pydap.  I've installed it and refreshed the binaries.

It still looks like there is a problem with the OpenDap plugin.  Is it working for you running out of the src tree?

**Comment by giumas** [comment]
How doesn't the plugin? If I ran the refreshed frozen application, the plugin seems to be recognized.

**Comment by jreadey** [comment]
I'm getting this error:

```
Traceback (most recent call last):
  File "hdf_compass/compass_viewer/frame.py", line 218, in on_resource_open
    self.open_url(url)
  File "hdf_compass/compass_viewer/frame.py", line 227, in open_url
    open_store(url)
  File "hdf_compass/compass_viewer/viewer.py", line 164, in open_store
    open_node(instance.root)
  File "hdf_compass/compass_viewer/viewer.py", line 121, in open_node
    f = container.ContainerFrame(node, pos=new_pos)
  File "hdf_compass/compass_viewer/container/frame.py", line 54, in __init__
    NodeFrame.__init__(self, node, size=(800, 400), title=node.display_title, pos=pos)
  File "hdf_compass/compass_viewer/frame.py", line 397, in __init__
    self.info.display(node)
  File "hdf_compass/compass_viewer/info.py", line 73, in display
    self.prop_text.SetLabel(describe(node))
  File "hdf_compass/compass_viewer/info.py", line 103, in describe
    kv_node = h(node.store, node.key)
  File "hdf_compass/opendap_model/model.py", line 285, in __init__
    self._keys = new_dset[self._key].attributes
AttributeError: 'NoneType' object has no attribute 'attributes'
```

With the url: http://test.opendap.org/dap/data/nc/coads_climatology.nc.

Does this work for you?

**Comment by giumas** [comment]
Nope! We need to investigate the issue.. Incidentally, `pydap` is getting some new work done to support python 3.

**Comment by giumas** [comment]
Try now after https://github.com/HDFGroup/hdf-compass/pull/165
@jreadey I am afraid that you have to re-freeze the application

**Comment by ghisvail** [comment]
Same question as with `hyo.bag`, do you guys plan to make source releases on PyPI alongside the wheels or should distributions rely on Github's ?

**Comment by giumas** [comment]
I would prefer PyPI: https://pypi.python.org/pypi/hdf_compass

**Comment by ghisvail** [comment]
The release tarball on PyPI is missing the `HDFCompass*` files located at the root of the source tree (icons, desktop file...).

**Comment by giumas** [comment]
I believe that those files are only used for freezing.. 
I don't know how it works the '.desktop' file that you added.Should it be added? Does it use the HDFCompass.ico?

**Comment by ghisvail** [comment]
Yes, otherwise the application cannot be [discovered](https://developer.gnome.org/integration-guide/stable/desktop-files.html.en) via the system menu. It uses the HDFCompass icons, so they should be added too.

**Comment by giumas** [comment]
Added in https://github.com/HDFGroup/hdf-compass/releases/tag/v0.6.0b7
I had to bump the version to `v0.6.0b7` since PyPI locks uploads with the same version

**Comment by ghisvail** [comment]
:+1:

**Comment by ghisvail** [comment]
How far do you guys think we are from the final `v0.6.0` release?

**Comment by giumas** [comment]
I don't see obstacles.. @jreadey, do you?

**Comment by jreadey** [comment]
I just did a Windows build after merging to the master branch, and I ran into this error on startup:
```
  
X:\HDF\HDFCompass\rel\0.6.0>HDFCompass_0.6.0.exe
PyInstaller Bootloader 3.x
LOADER: executable is X:\HDF\HDFCompass\rel\0.6.0\HDFCompass_0.6.0.exe
LOADER: homepath is X:\HDF\HDFCompass\rel\0.6.0
LOADER: _MEIPASS2 is NULL
LOADER: archivename is X:\HDF\HDFCompass\rel\0.6.0\HDFCompass_0.6.0.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\john\AppData\Local\Temp\_MEI16122
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is X:\HDF\HDFCompass\rel\0.6.0\HDFCompass_0.6.0.exe
LOADER: homepath is X:\HDF\HDFCompass\rel\0.6.0
LOADER: _MEIPASS2 is C:\Users\john\AppData\Local\Temp\_MEI16122
LOADER: archivename is X:\HDF\HDFCompass\rel\0.6.0\HDFCompass_0.6.0.exe
LOADER: SetDllDirectory(C:\Users\john\AppData\Local\Temp\_MEI16122)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\john\AppData\Local\Temp\_MEI16122\HDFCompass_0.6.0.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\john\AppData\Local\Temp\_MEI16122\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Users\john\AppData\Local\Temp\_MEI16122
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename HDFCompass_0.6.0.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\john\AppData\Local\Temp\_MEI16122
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth__tkinter.py
LOADER: Running pyi_rth_win32comgenpy.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running pyi_rth_mplconfig.py
LOADER: Running pyi_rth_mpldata.py
LOADER: Running HDFCompass.py
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:190 > Python 2.7.0 64bit on Windows 7 (AMD64)
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:192 > numpy 1.10.0.post2
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:193 > matplotlib 1.4.3
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:194 > wxPython 3.0.2.0
DEBUG   hdf_compass.compass_viewer.viewer.load_plugins:211 > h5py 2.5.0
Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "C:\Users\John\hdf-compass\hdf_compass\compass_viewer\viewer.py", line 253, in run
  File "C:\Users\John\hdf-compass\hdf_compass\compass_viewer\viewer.py", line 216, in load_plugins
  File "c:\users\john\appdata\local\temp\pip-build-aekvrr\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 36
3, in load_module
  File "C:\Users\John\hdf-compass\hdf_compass\bag_model\__init__.py", line 16, in <module>
  File "c:\users\john\appdata\local\temp\pip-build-aekvrr\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 36
3, in load_module
  File "C:\Users\John\hdf-compass\hdf_compass\bag_model\model.py", line 23, in <module>
  File "c:\users\john\appdata\local\temp\pip-build-aekvrr\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 36
3, in load_module
  File "c:\python27\lib\site-packages\hydroffice\bag\__init__.py", line 13, in <module>
  File "c:\users\john\appdata\local\temp\pip-build-aekvrr\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 36
3, in load_module
  File "c:\python27\lib\site-packages\hydroffice\bag\bag.py", line 9, in <module>
  File "c:\users\john\appdata\local\temp\pip-build-aekvrr\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 36
3, in load_module
  File "c:\python27\lib\site-packages\lxml\isoschematron\__init__.py", line 51, in <module>
  File "lxml.etree.pyx", line 3310, in lxml.etree.parse (src\lxml\lxml.etree.c:72517)
  File "parser.pxi", line 1791, in lxml.etree._parseDocument (src\lxml\lxml.etree.c:105979)
  File "parser.pxi", line 1817, in lxml.etree._parseDocumentFromURL (src\lxml\lxml.etree.c:106278)
  File "parser.pxi", line 1721, in lxml.etree._parseDocFromFile (src\lxml\lxml.etree.c:105277)
  File "parser.pxi", line 1122, in lxml.etree._BaseParser._parseDocFromFile (src\lxml\lxml.etree.c:100227)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:95786)
  File "parser.pxi", line 618, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:94818)
IOError: Error reading file 'C:\Users\john\AppData\Local\Temp\_MEI16122\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl'
: failed to load external entity "file:///C:/Users/john/AppData/Local/Temp/_MEI16122/lxml/isoschematron/resources/xsl/XS
D2Schtrn.xsl"
HDFCompass returned -1
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: -1)
LOADER: Doing cleanup
LOADER: Freeing archive status for X:\HDF\HDFCompass\rel\0.6.0\HDFCompass_0.6.0.exe

```

Is XSD2Schtrn.xsl some late addition as a resource?

**Comment by giumas** [comment]
I have personally changed the PyInstaller hook for adding the collection of all the files under "lxml/isoschematron/resources": https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-lxml.isoschematron.py

What version of PyInstaller are you running? The fact that your output says: ``PyInstaller Bootloader 3.x``, not ``PyInstaller Bootloader 3.2`` makes me guess that you might have an old development version installed.

**Comment by jreadey** [comment]
It's pytinstaller v 3.0.

Can I just do a ``pip install pyinstaller --upgrade``?

**Comment by giumas** [comment]
Yes, ``pip install --upgrade pyinstaller``. I wonder how you have been able to freeze on Windows before..

**Comment by jreadey** [comment]
I think I had some hacks to my original pyinstaller code.  Anyway, it works with the latest pyinstaller.

Here's the link to the Windows build: https://s3.amazonaws.com/hdfgroup.download/HDFCompass/0.6.0/HDFCompass.exe.
I tried it out for HDF5 and BAG and didn't see any problems.

**Comment by giumas** [comment]
![2016-06-12_20-00-21](https://cloud.githubusercontent.com/assets/2849257/15994650/541f5afa-30d8-11e6-996e-57c57df0088d.png)

**Comment by giumas** [comment]
The geo-array is not working, and it is reverting to a generic plot:
![2016-06-12_20-04-49](https://cloud.githubusercontent.com/assets/2849257/15994680/f6aa6076-30d8-11e6-95e5-383b20689794.png)

Do you have ``cartopy`` installed? Does the geo-array work without freezing?
If all work, you should get something like this (note the shading and the geographic coordinates):
![2016-06-12_20-09-22](https://cloud.githubusercontent.com/assets/2849257/15994709/91a93c28-30d9-11e6-98d4-5ec74a57886f.png)


Why ``matplotlib 1.4.3``? It does not have the hill shading.
![hdfcompass_2016-06-12_20-07-15](https://cloud.githubusercontent.com/assets/2849257/15994694/473a0bf4-30d9-11e6-8177-8ffd87a0dcb7.png)

**Comment by jreadey** [comment]
Oops, looks like I used an old VM for the build.  Let me try with the correct one.

**Comment by jreadey** [comment]
Ok, there's a new Window's binary here: https://s3.amazonaws.com/hdfgroup.download/HDFCompass/0.6.0/HDFCompass.exe.  
BAG plots are working correctly, and the About Box version number is fixed.

**Comment by ghisvail** [comment]
AFAIC, everything is ready on the packaging side. I can submit the `hdf-compass` package immediately after the release of `v0.6.0` on PyPI. Whilst the package is under review, I can focus on the optional dependencies such as `hydroffice.bag`, `pydap` and `cartopy`.

**Comment by giumas** [comment]
@jreadey It works on my machine

**Comment by jreadey** [comment]
@giumas - can you do the PyPI release?

**Comment by giumas** [comment]
@jreadey of course, yes.We should also add a release tag on GitHub. Let me know when you decide that is time.

**Comment by jreadey** [comment]
Ok - done!

**Comment by giumas** [comment]
I have just discovered this: https://github.com/HDFGroup/hdf-compass/blob/develop/spec.json#L2

**Comment by giumas** [comment]
The py2app script is also outdated.. Actually, I did not test it since a while. Do you? https://github.com/HDFGroup/hdf-compass/blob/develop/setup.py2app.py#L49

**Comment by giumas** [comment]
This file is outdated: https://github.com/HDFGroup/hdf-compass/blob/develop/README.txt

**Comment by jreadey** [comment]
No, I haven't used py2app since we switched to using pyinstaller for both windows and Mac.  Delete it?
The version strings hidden everywhere are a pain.

**Comment by jreadey** [comment]
I can delete README.txt as well.  Anything else?

**Comment by giumas** [comment]
I am double-checking.. it doesn't seem to me that these small issues require a new tag

**Comment by giumas** [comment]
Do you plan to provide the dmg for Mac?

**Comment by jreadey** [comment]
Yes, but I won't be able to get to it this week - I'm traveling.

**Comment by giumas** [comment]
One more: https://github.com/HDFGroup/hdf-compass/blob/develop/docs/conf.py#L60

**Comment by giumas** [comment]
The license year is not updated: https://github.com/HDFGroup/hdf-compass/blob/develop/docs/license.rst

**Comment by giumas** [comment]
Are you freezing with `console=True` and `debug=True`? https://github.com/HDFGroup/hdf-compass/blob/master/HDFCompass.1file.spec#L89

**Comment by jreadey** [comment]
Yes.

**Comment by giumas** [comment]
Here we go: https://pypi.python.org/pypi/hdf_compass/0.6.0

**Comment by giumas** [comment]
@jreadey Can you create an account on PyPI? I believe that it is a good idea if I add you.. just in case.

**Comment by jreadey** [comment]
I have a PyPI account.  Userid is: john_readey.

**Comment by giumas** [comment]
Just added

**Comment by giumas** [comment]
@ghisvail This ticket is getting too long.. and capturing too much stuff. I would like to close it as soon as the debian package is accepted!

**Comment by ghisvail** [comment]
Since `v0.6.0` is out, it is now my turn to work. I'll report here if I have issues / comments, but it should be fine. I will close it once the package is submitted.

Cheers,

**Comment by ghisvail** [comment]
I need a `tar.gz` release on PyPI please.

**Comment by giumas** [comment]
added

**Comment by giumas** [comment]
@ghisvail updates? can we close this ticket?

**Comment by ghisvail** [comment]
It is currently sitting in the NEW queue for approval by the release team. Will close once it is accepted.

**Comment by ghisvail** [comment]
hdf-compass is now available in Debian. Closing.

**Comment by jreadey** [comment]
@ghisvail - cool!  Does this mean I can just do Apt-get on a recent Debian install to get it?  What's the package name?

**Comment by ghisvail** [comment]
https://packages.debian.org/sid/hdf-compass

It will transition to Debian Stretch (Debian testing, future stable) tomorrow.
