### ISSUE TITLE
Blog post on 0.6.0 Compass Release

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf-compass#170]
Write blog post for HDF Group website that highlights new features in this release (primary the BAG plugin).

Related to #139.

**Comment by jreadey** [comment]
@giumuas - do you think you would be able to do this?

**Comment by giumas** [comment]
I am happy to do this, but I am afraid that I cannot do it soon. So feel free to go ahead if you have time to do it now.

**Comment by giumas** [comment]
My apologies! It would be also too late now.
