### ISSUE TITLE
row column ordering

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf-compass#174]
For HDF5 datasets, HDF Compass displays a transposed column ordering compared to HDFView.
Either make the display consistent with HDF View or add a user default option for row major vs column major display.

**Comment by jreadey** [comment]
@andrewcollette - was the current ordering a deliberate decision when Compass was first created?

@epourmal favors the HDFView style ordering.

**Comment by andrewcollette** [comment]
I think it was a random decision.  Picking one or the other is probably a better approach than having an option.

**Comment by epourmal** [comment]
John and all,

My concern was that tuple that represents the shape doesn't correspond to how array is displayed. For example, compass reports an array being 4x6, but displays it as 6x4.

Elena

Sent from my iPhone

On Jul 11, 2016, at 6:17 PM, Andrew Collette <notifications@github.com<mailto:notifications@github.com>> wrote:

I think it was a random decision. Picking one or the other is probably a better approach than having an option.

##

**Comment by andrewcollette** [comment]
Looks like a more random decision than I thought! :)

**Comment by jreadey** [comment]
This is fixed thanks the oyarzun's pr.
