### ISSUE TITLE
export / copy to clipboard

### ISSUE THREAD

**Issue by michaelsippel** [HDFGroup/hdf-compass#175]
We would like to implement the feature to export data/copy to clipboard in tab-delimitation or CSV from the array-frame in addition the plot function.

I would add two buttons to the toolbar in the array-frame: one to copy the selection of the dataset in tab-delimited format to the clipboard and one to export the selected data in CSV-format.
This would make the exchange with excel/oo-calc and other data evaluation easier.

To add this feature I would implement in `hdf_compass/compass_viewer/array/frame.py` in the ArrayFrame class the functions `on_copy` and `on_export`. Should I bind them to the buttons in `init_toolbar` or is this done elsewhere?

**Comment by oyarzun** [comment]
Added in PR #177
