### ISSUE TITLE
Heretic proposal about switching to PySide2

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#184]
It seems that (sadly) there is a lack of active development as well as a concrete road map to have a stable port of Wx for Python 3.5: https://github.com/wxWidgets/Phoenix/issues/101

Quite surprisingly, the bounty to push the Phoenix development is lacking substantial funds: https://groups.google.com/forum/#!topic/wxpython-users/-ey4AysT9ao 

Given that PySide2 is moving toward a stable release (http://wiki.qt.io/PySide2), I would propose to think on a possible switch in a few months.. 

The amount of work for making it happens is surely large, but it could be a good long-term decision for the health of this project.

**Comment by jreadey** [comment]
Yikes!  That will be a big chunk of work.
Beyond the source changes we'll need to verify that there are no issues with pyinstaller.

Are there any licensing issues to be concerned about with PySide/Qt?

**Comment by ghisvail** [comment]
I would suggest using one of the shim layers for Qt, like [`qtpy`](https://github.com/spyder-ide/qtpy). That way you can keep the licensing of the code as is ([`spyder`](https://github.com/spyder-ide/spyder) is BSD licensed for instance), and users can choose which Qt Python implementation they want.

**Comment by ghisvail** [comment]
FYI, Debian will be dropping Python 2 for its next release cycle (`Buster`). If `hdf-compass` fails to work with Python 3 when it happens, I am afraid I will have no choice but remove it from the archive unfortunately.

**Comment by giumas** [comment]
Well, the only current big issue is `wxPython`. Does `Buster` have `3.0.2`? 

- If NO, which `wxPython` release is available?
- If YES, did you try to install and run using `pip install -e .`? Which errors are you getting?

**Comment by ghisvail** [comment]
`wxPython` is still available in Debian Stretch (to be released soon), so `hdf-compass` is safe for this release. However, Debian Buster (to be released in ~2 years) will support Python 3 exclusively, hence my warning.

**Comment by giumas** [comment]
I see! Is `wxPython` currently present on Debian Stretch for Python 3?

**Comment by ghisvail** [comment]
No, it is only packaged for Python 2 (what is referred upstream as wxpython *classic*, I believe)

**Comment by giumas** [comment]
This makes the issue much more wider than just HDFCompass! 
However, at today, my impression is that both `WxPhoenix` and `Pyside2` are not stable for Python 3. Let's see if something will change in the next months.

**Comment by jreadey** [comment]
@giumas - Granted it's not Python, but something like electron could be a possibility: http://electron.atom.io/.  We've already done a lot of work to create a HTML5-based web ui for HDF - see https://data.hdfgroup.org/.  I'd need to think how the Compass plug-in architecture cold be adopted.

**Comment by giumas** [comment]
@jreadey Well, I have started this by putting 'heretic' in the title! Do you envision to open new window browsers to emulate the current user experience?

**Comment by jreadey** [comment]
No I think electron creates top-level windows that are native.  If you've used the Slack desktop app, that is built with electron, but looks just like a regular app.

**Comment by ghisvail** [comment]
Anyway, I suggested using a Qt shim layer (using `qtpy` for instance) so that any Qt backend for Python can be supported, including PySide 2 in the future.

Assuming model, view and controller are cleanly separated in the design of `hdf-compass`, it should be less effort to migrate to Qt than porting the code base to a different language (Node) and ecosystem (Electron).

**Comment by jreadey** [comment]
That does seem like a more practical approach. 👍 
Does PySide 2 properly support Python 3?  It wasn't clear from reading their wiki.

**Comment by giumas** [comment]
@ghisvail I agree on the current advantages of a Qt shim layer, but I am afraid of the additional abstraction layer. Once that `Pyside2` is stable, it might become really not worthwhile.

@jreadey I have 3 points:

- There is a fork of `Pyside` that supports Python 3 (http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyside), but the deep issue is that `Pyside` wraps Qt4 (that is not more maintained).
- The issues with `Pyside2` are that it is still not stable (but a large amount of efforts from Qt company is being put on it: http://wiki.qt.io/PySide2), and that it wraps Qt5 (that on Windows does not support Visual Studio 2008 which is the official compiler for Python 2.7). Other that these 2 issues (the first is temporary, the second does not count if `HDFCompass` will become Python3-only), there are a lot of pros.
- Switching from Wx to Qt world would require a massive amount of re-coding. I would guess more than just moving from WxPython classic to Phoenix, but with the advantage of then relying on a GUI library that is directly maintained by the QT Company.

And 1 question that @jreadey might already know the answer: is the HDF Group willing to put efforts and/or resources on the switch? This answer would be useful to define a development plan for `HDFCompass` based on one of the various options.

**Comment by jreadey** [comment]
@giumas - I'm not speaking officially for the company, but at this point I think it's unlikely that HDF Group would commit to the porting effort.  Beyond maintenance most larger projects happen at THG because someone is willing to fund the work.   If you know of any potential sponsors, let's talk offline.

**Comment by giumas** [comment]
@jreadey I don't know of any potential sponsors. As in the past, I am glad to provide a contribution to whatever you decide to do with `HDFCompass`.

**Comment by jreadey** [comment]
@giumas - thank you for your contributions.

Another alternative would be to see if we can get a few more volunteers to work collaboratively on the port.  Anyone who is interested is welcome to post here or contact me or @giumas directly.

**Comment by giumas** [comment]
@ghisvail I have pushed a Python 3 branch that uses Phoenix (https://github.com/HDFGroup/hdf-compass/issues/186).

@jreadey Given the lack of volunteers, I would close this ticket.

**Comment by jreadey** [comment]
@giumas - have you seen any problems with the Python 3 build of Compass?

**Comment by ghisvail** [comment]
> @ghisvail I have pushed a Python 3 branch that uses Phoenix (#186).

Nice. Looks like wxPython classic is now unmaintained and all development efforts are pushed towards [Phoenix](https://groups.google.com/forum/#!topic/wxpython-dev/aenkS6q_SJs). So, this is a good move IMO.

 > @jreadey Given the lack of volunteers, I would close this ticket.

Please keep it open but rename it to something else reflecting the topic of this thread, i.e. future Python 3 support.

**Comment by giumas** [comment]
@jreadey the issues that I had on Python 3 are described in https://github.com/HDFGroup/hdf-compass/issues/186

**Comment by jreadey** [comment]
I'm closing this issue - we can re-open in the future if there's support for moving off of Phoenix.
