### ISSUE TITLE
Help Search has no Results

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf-compass#33]
Help/Search menu does not show many results - just About/Hide/Quit menu items.

**Comment by giumas** [comment]
I believe that this is a Mac-specific issue.

**Comment by jreadey** [comment]
The mac specific feature is the Help Search box (of limited usefulness in my opinion).  But there's no "Online Manual" item as the Windows build has.

So proposal is that Mac have two items under help: Search and "Online Manual"

**Comment by giumas** [comment]
> But there's no "Online Manual" item as the Windows build has.

Are you sure? I get the "Online Manual" menu item both from script and from app:

![capture](https://cloud.githubusercontent.com/assets/2849257/10779139/0fa515e2-7d03-11e5-8656-6ce6e3fa84ba.PNG)

**Comment by jreadey** [comment]
Yes, you are correct!

Closing this issue.
