### ISSUE TITLE
Open Resource fails on Windows

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf-compass#42]
OpenResource with a OpenDap resource: http://nsidc.org/opendap/MOSA/MYD10CM.005/2003.02.01/MYD10CM.A2003032.005.2008056200320.hdf works on Mac, but fails on Windows.

**Comment by giumas** [comment]
I have just attempted to open that link with the `develop` branch, and it works on Win7 64bit:
![capture](https://cloud.githubusercontent.com/assets/2849257/10260408/3efcfa90-6943-11e5-84c6-5bcc997553ea.PNG)

@jreadey , do you remember if the bug was on a different Windows OS?

**Comment by jreadey** [comment]
This looks like a dup of #60
