### ISSUE TITLE
Test data set and 'Open samples' item in the 'File' menu

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#51]
It would be nice to have a stand-alone 'test_data' repository with example files to be used for testing. For instance, such a repo could replace `url = "file:///Users/andrew/Documents/Compass/Demo files/2_5.hdf5"` in `hdf5_model\test.py`

**Comment by jreadey** [comment]
There are the files here: https://github.com/HDFGroup/hdf5-json/tree/master/data/hdf5, but I don't think it's possible to reference just one file from a github repo.

How about I include a test file as part of this repo?

From the point of view of users of the binary installer, it would be nice to have the install copy the test file and documentation that instructs them to open the file to verify their installation.

**Comment by giumas** [comment]
It would be surely a simple effective solution.. A tiny example file might be also added for Esri grid and for whatever future plugin that is file-based.

Could you expand a bit on what you mean with the last sentence? Are you thinking to something like a NSIS installer (for Windows) or simply a tarball with the frozen application, a manual in pdf and a sub-folder with the test data?

**Comment by jreadey** [comment]
We have py2app dmg binaries for Mac and PyInstaller one-click executables for Windows here: https://www.hdfgroup.org/projects/compass/.  
Actually the binaries integrate better with the OS then running from the repo.  Try it if you haven't already and you'll see what I mean.

One question I got from someone who ran the dmg-install version was: were to get a file to view?  So having at least one file provided by the installer would be useful.

**Comment by giumas** [comment]
I have already tested both the Window and the Mac binaries (although this latter was crashing as described here: https://github.com/HDFGroup/hdf-compass/issues/49). They are very handy when you don't want to deal with dependencies and python installation. 

My question was more on whether you want to 'bundle' the test files all in a one-file executable, in a one-folder executable or in an installer that can also be used to add shortcuts to the menu program.

**Comment by jreadey** [comment]
I think an installer for Windows would be best, but as far as I know pyinstaller.py only creates executables.
This may be worth looking into to create a Windows installer: http://www.jrsoftware.org/isinfo.php.

**Comment by giumas** [comment]
Although famous, I have never created an installer with Inno Setup. I am more familiar with NSIS: http://nsis.sourceforge.net/Main_Page. I believe that it should provide the features that you have in mind. It might be useful try to quickly list the most important.. and see which of the 2 installer creators matches better the query.

**Comment by giumas** [comment]
After having looked a bit deeper at `pyinstaller`, I would suggest to simply bundle the test files with the single-file executable. 

At run time, the loader unzip the content to a temporary folder (thus is better to add small test files). Thus, we could add to the `File` menu a call like `Open test file folder`.

If you add the `test_data` folder on a `develop` branch, I will show you in practice what I mean..

**Comment by giumas** [comment]
@jreadey Did you try the "Open samples ..." item in the BAG Explorer "File" menu? This is what I had in mind here:

> At run time, the loader unzip the content to a temporary folder (thus is better to add small test files). We could then add to the File menu a call like Open test file folder.

**Comment by giumas** [comment]
The test data set is now present. The 'Open samples' item will not be introduced (at least, in the next release).
