### ISSUE TITLE
Linux binary for 0.5.1

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#53]
After having installed the `pyinstaller` dev (https://github.com/pyinstaller/pyinstaller/archive/develop.zip) to fix this issue: https://github.com/pyinstaller/pyinstaller/issues/885, I have been able to freeze `HDFCompass` on `Ubuntu 15.04`. ~~Here a testing binary: https://github.com/giumas/hdf-compass/releases/download/5.0.1.Ubuntu.x64/HDFCompass.out~~

Was that issue the reason of missing binaries for some major Linux distros?

**Comment by jreadey** [comment]
I just didn't have time for it when I was doing the initial Mac and Windows release.
Going forward, I'd like to create a system that does a nightly release build.

@giumas, I tried out your binary on my CentOS 6.5 system (x64) and got this error:

```
Traceback (most recent call last):
  File "<string>", line 36, in <module>
  File "/home/test/miniconda/lib/python2.7/site-packages/PyInstaller-2.1.1.dev0-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 416, in load_module
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIuPuJfs/libstdc++.so.6)
```

Any thoughts on what is going wrong?

**Comment by giumas** [comment]
For the nightly release build for Windows, what do you have in mind? Something like Appveyor (http://www.appveyor.com/) or more like Jenkins (https://jenkins-ci.org/)? Does the HDFGroup already have a mechanism for other libraries that may be adapted?

About your error, I believe that the issue is that Centos usually has older libraries than Ubuntu (as also cited here: http://unix.stackexchange.com/a/15476/95180). 

By the way, I have created a binary with a Centos 6.5 x86_64 VM that seems to work (I had to use also on that platform the Pyinstaller dev installation as I previously posted). You can test if the Centos binary works on your machine from here: https://github.com/giumas/hdf-compass/releases/download/5.0.1.Centos.6.5.x86_64/HDFCompass.out 

Using the Ubuntu's binary on the Centos VM, I got the same error as you. Vice versa, on Ubuntu the Centos binary works (although with a bunch of warnings).

**Comment by jreadey** [comment]
The latest version runs, but if I try to open a file I get an error: "bar_root doesn't exist".  Some cross-talk with the BAG plugin?

Regarding builds, I was thinking to setup an HDF Group build machine.  Can appveyor do pyinstaller builds?

For Mac builds we want to be able to sign the binaries.

**Comment by giumas** [comment]
Oh yes, a missing exception catch.. I have just updated the binary: https://github.com/giumas/hdf-compass/releases/download/5.0.1.Centos.6.5.x86_64/HDFCompass.out

Appveyor can surely do the `pyinstaller` job, and it is free for open source projects.

**Comment by jreadey** [comment]
@giumas, in your plugin, are you using the canhandle method to determine if the file is a BAG file or not?
Say: h5py.is_hdf5(path) and 'bar_root' in f?  

I'll research Appveyor.

**Comment by giumas** [comment]
@jreadey : yes, as you can see here: https://github.com/giumas/hdf-compass/blob/master/bag_model/__init__.py#L71-77 , the issue was in the called method `is_bag`: https://github.com/giumas/hdf-compass/blob/master/bag_model/openns/bag/bag.py#L6-21
