### ISSUE TITLE
Running with pythonw

### ISSUE THREAD

**Issue by durden** [HDFGroup/hdf-compass#54]
I typically use PyQt instead of wx so I'm not sure if this is considered common knowledge or not, but I had to run this application with 'pythonw' instead of the standard python as the README suggested.  Should this be mentioned in the README?

Again, I have no experience with wx so I spend a while looking into this error when using the command from the README:

> This program needs access to the screen.
> Please run with a Framework build of python, and only when you are
> logged in on the main display of your Mac.

I'm using Python from the Anaconda distribution on OS X 10.10 which already setup pythonw to point to a Framework version of Python.  I didn't have to create any bash scripts to fake the python executable when running inside a virtualenv as described [here](http://www.georgevreilly.com/blog/2015/09/20/RunSnakeRun-WxPython-Brew-Virtualenv.html) and [here](http://wiki.wxpython.org/wxPythonVirtualenvOnMac) but maybe those could be useful references too.

**Comment by jreadey** [comment]
Right, this seems like a quirk of Anaconda with wx.  I've revised the README, to direct Mac/Anaconda users to use pythonw.
