### ISSUE TITLE
Frame icon

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#55]
The application does not show the frame icon when executed as script. The frozen application only shows the frame icon on the initial frame.
The 'About' dialog does not show up the application icon, but a default icon. 
On Windows, the application icon is not displayed on the task bar.

**Comment by jreadey** [comment]
This is fixed in the develop branch (thanks to @giumas pull request).
Will close the issue when develop is merged to master.

**Comment by jreadey** [comment]
Actually I think it will be best to close issues as they are resolved in the develop branch (to avoid the issue list with getting to cluttered)

We'll document which issues are resolved by the official release in the release notes.
