### ISSUE TITLE
Milestone lists?

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#61]
@jreadey : a shared list of milestones for next release (0.6.0) and for the following ones could be useful to prioritize development efforts, and to avoid overlaps. 

From my point of view, a possible initial list could be:

* ~~put `HDFCompass` on pypi (so that users can execute `pip install hdf_compass`)~~
* ~~add a common namespace `hdf_compass` for all the packages (e.g., `hdf_compass.compass_model`, `hdf_compass.compass.viewer`) -> PR: https://github.com/HDFGroup/hdf-compass/pull/62~~
* adopt the Python `logging` mechanism (*only for development/debugging aims*): PR https://github.com/HDFGroup/hdf-compass/pull/64
* unify the freeze mechanism to `pyinstaller` (dropping the existing `py2app` workflow) ~~and to bundle data with the resulting binaries~~: https://github.com/HDFGroup/hdf-compass/issues/49, ~~https://github.com/HDFGroup/hdf-compass/issues/51~~: PR: https://github.com/HDFGroup/hdf-compass/pull/65
* create CI with Travis CI and Appveyor
* follow PEP8: https://github.com/HDFGroup/hdf-compass/issues/52
* add BAG plugin: https://github.com/giumas/hdf-compass/tree/bag_model
* fix OpeNDAP plugin issue: https://github.com/HDFGroup/hdf-compass/issues/60
* reach Python 2-3 compatibility: https://github.com/HDFGroup/hdf-compass/issues/46
* access manual from within HDFCompass (e.g., by a call to open a `manual.pdf`)
* collect all the repeated code snippets as helper functions in a `hdf_compass.common` package
* review the icon embedding mechanism: https://github.com/HDFGroup/hdf-compass/issues/63

@jreadey proposed:
* Tree View of object hierarchy (@hyoklee is looking into this)
* Recent file history
* Recent Resource history
* Easier way to view attributes
* Support for indexed images
* Inclusion of sample data formats
* About box showing which plugins or available
* Repurpose Window menu item to select from a list of top-level windows
* Signed binaries for Mac/Windows
* Support for older OS X releases (@jreadey put out a Mountain Lion compatible release)
* Frozen binary for Linux (do we need different binaries for various Linux flavors?): https://github.com/HDFGroup/hdf-compass/issues/53
* MSI Installer for Windows
* ~~Add Home button to navigation toolbar (easy): https://github.com/HDFGroup/hdf-compass/issues/15: PR: https://github.com/oyarzun/hdf-compass/commit/f6caa8106077a3f325db9527b7b229e11fca4e61~~
* Bad cell selection for 1D datasets (easy): https://github.com/HDFGroup/hdf-compass/issues/18
* Display element index value: https://github.com/HDFGroup/hdf-compass/issues/20
* Clipboard support (medium?): https://github.com/HDFGroup/hdf-compass/issues/21
* Improve the display of linked datatypes (medium): https://github.com/HDFGroup/hdf-compass/issues/25
* Add graph view of object structure (hard): https://github.com/HDFGroup/hdf-compass/issues/26

Some of these milestone may require substantial code re-arrangement. So I believe that PR related to this list should be directed to `develop` branch (and to eventually backport to just a selection of them).

**Comment by hyoklee** [comment]
I like the idea of dropping py2app. PyInstaller seems to work well for Compass on Mac so I don't know why py2app is needed.

**Comment by jreadey** [comment]
@andrewcollette, do you recall the motivation for using py2app for Mac installers rather than pyinstaller?

@hyoklee, you were able to create an installable app on the Mac?  Send me a link to the image & I'll try installing it on a clean system.

**Comment by hyoklee** [comment]
Here's the link: ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/joe/h5compass_mavericks

**Comment by jreadey** [comment]
@giumas - Does putting on pypi make sense for Compass?  If I understand correctly, "pip install hdf_compass" is not going to bring in wxPython, HDF library, etc.  So I'm not sure how much value there is over just doing "git clone .."

**Comment by jreadey** [comment]
I'm supportive of @giumas feature list above. (with the question about pypi)
Other items (everyone feel free to up vote or down vote these):

* Tree View of object hierarchy (@hyoklee is looking into this)
* Recent file history
* Recent Resource history
* Easier way to view attributes
* Support for indexed images
* Inclusion of sample data formats
* About box showing which plugins or available
* Repurpose Window menu item to select from a list of top-level windows

In addition there are some items that are more in the category of release management:

* Signed binaries for Mac/Windows 
* Support for older OS X releases (I just put out a Mountain Lion compatible release)
* Frozen binary for Linux (do we need different binaries for various Linux flavors?) 
* MSI Installer for Windows

I'd like to target an "official" next release for early Nov, so we should keep our ambitions in check!

**Comment by giumas** [comment]
@jreadey: we create python wheels and put on the `setup.py` all the dependencies: https://wheel.readthedocs.org/en/latest/#defining-conditional-dependencies
This implies that, when you run `pip install hdf_compass`, `pip` will install all the required dependencies.

**Comment by jreadey** [comment]
@giumas: but for example, pip install h5py, doesn't install hdf5 libraries...

**Comment by jreadey** [comment]
Also some possible features from issues with the 'enhancement' tag (with my facile assessment of easy/medium/hard):

* #15 - Add Home button to navigation toolbar (easy)
* #18 - Bad cell selection for 1D datasets (easy)
* #20 - Display element index value
* #21 - Clipboard support (medium?)
* #25 - Improve the display of linked datatypes (medium)
* #26 - Add  graph view of object structure (hard)

Again, up votes/down votes are appreciatted

**Comment by giumas** [comment]
> @giumas: but for example, pip install h5py, doesn't install hdf5 libraries...

@jreadey, from my understanding based on this link: http://docs.h5py.org/en/latest/build.html, several package managers as Anaconda (or wheels repository as the glorious http://www.lfd.uci.edu/~gohlke/pythonlibs/#h5py) already include the hdf5 libraries. And they can also use `pip`. 

This would mean that adding HDFCompass on PyPi would cover many possible user configurations. And the installation instructions would be reduced to 2 steps: 

1. use your favorite package manager to install `h5py`; 
2. `pip install hdf_compass` for HDFCompass with all the remaining dependencies.

It looks like @andrewcollette has this related ticket https://github.com/h5py/h5py/issues/602 open on `h5py` repository. The future of this ticket could (or not) imply that the installation instruction simplify to just step 2.

**Comment by andrewcollette** [comment]
@giumas, @jreadey, I am happy to provide my perspective on packaging.  While I understand the desire to use the "standard" Python mechanism of pip, I would strongly urge *not* trying to distribute HDF Compass in this fashion.  Here are a few reasons why; I've tried to edit them down for length.

First, although HDF Compass is written in Python, one of the most important goals is that it should work exactly like a native application.  Distributing software libraries is what pip/PyPI/conda are optimized for; they work less well, if at all, for apps.  For example, placing the HDFCompass.app bundle in the appropriate place in the file system will register file extensions.  Likewise with a Windows MSI installer.  These are the appropriate ways to distribute apps for the major platforms.

Second, I think it's easy to underestimate the problems involved with distributing code with large binary dependencies like wxPython and HDF5.  Conda is great, but ultimately it relies on someone doing the integration, maintaining the build recipe, checking for conflicts, etc.  Famously, Anaconda shipped a build of HDF5 without GZIP support (!) for quite a while, not because the people involved were incompetent but because packaging is a hard job and it was hard to keep up with all the options.  So it's not a matter of throwing in a setup.py file and being done.  Pip-based distribution is an open-ended commitment from the HDF Group to support PyPI, Conda, etc., as additional channels on top of Mac/Windows/Linux binaries.

In response to why py2app instead of PyInstaller... as I recall, py2app provided a much better native experience.  If you go with PyInstaller, be sure to check for things like drag & drop of files onto the app icon (app running and closed) open the files, de-minimizing when the dock icon is clicked, and so forth.  Simply seeing the app launch is not enough.

The logging module is fine, but for the love of God please do not expose the log messages to the user in a silly little logging pane. @jreadey knows my thoughts on this. :)

Overall, I think it's great that folks are interested enough in Compass to have this conversation.  Good news!

**Comment by giumas** [comment]
@andrewcollette : Given your strong opinion on that, I deleted the PyPi support from the above list (although much bigger applications are on PyPi as, for instance, https://pypi.python.org/pypi/mayavi).

About:
> In response to why py2app instead of PyInstaller... as I recall, py2app provided a much better native experience. If you go with PyInstaller, be sure to check for things like drag & drop of files onto the app icon (app running and closed) open the files, de-minimizing when the dock icon is clicked, and so forth. Simply seeing the app launch is not enough.
I am monitoring since a while the issues on https://github.com/pyinstaller/pyinstaller/issues , and I didn't notice open tickets of such a kind (gui user experience).

On the logging, I totally agree with you. Only for development/debugging aims.

@jreadey , about:
> * Inclusion of sample data formats
* Do you have in mind to put them in something like a `samples` folder in the root of the repository?
* Where can I find the example of hdf5 images used to develop/test `hdf_model`? 

@jreadey , please feel free to modify the above milestone list (and the whole ticket) or, if you prefer, to close this and open yourself a ticket on the topic.

**Comment by jreadey** [comment]
@andrewcollette, thanks for your comments!  BTW, feel free to suggest other features you'd like to see in Compass.

Let's verify if the pyinstaller issues are resolved now.  If so, moving to pyinstaller for everything will be easiest.

We can keep this issue open for now.  Once we've closed in on the feature set, I'll open a new issue which lists the set of features for the next release.  I'll link each feature to it's own issue so those can be tracked separately.

**Comment by giumas** [comment]
> * Do you have in mind to put them in something like a samples folder in the root of the repository?

Shame on me, I have just seen the `data` folder!

**Comment by jreadey** [comment]
I just created that last night.  I don't want to bulk up the repo, but I think it would be nice for each file-based plugin to have at least sample data file.

For the Mac DMG installer, it should be a simple manner to setup the data folder at install time.
We can do the same for Windows once we have a MSI installer.

**Comment by giumas** [comment]
PyInstaller has a mechanism to add whatever files inside the binary. I did this for the GDAL auxiliary data at this row of the `osgeo` hook that I have contributed: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-osgeo.py#L41

Then, at run-time, these files are unzipped in a temporary folder (together with all the dynamic libraries and the application loader). The path of this temporary folder is stored in `sys._MEIPASS` (http://stackoverflow.com/questions/22472124/what-is-sys-meipass-in-python) and thus the `data` folder can be accessed from a menu call (referring to `os.path.join(sys._MEIPASS, 'data')`). This temporary folder is recreated (and destroyed) at each execution.

**Comment by giumas** [comment]
Another improvement could be to collect all the repeated code snippets as function in a `common` package (https://github.com/HDFGroup/hdf-compass/issues/57).

**Comment by jreadey** [comment]
Re: installing sample data files, upon reflection, there doesn't seem a clean way to do this.  I think that the default location of the file open dialog should properly be the user's home folder.  If we dump some data files into the application directory, that's not really helping the first time user.

**Comment by giumas** [comment]
To avoid the additional complications of an installer for Windows, we could simply check in the user folder for the 'data' folder at the HDFCompass initialization. If not present, copying the 'data' folder from the temporary application folder. Thus the copy would happen only at first run for each user. This solution would leave those files there.. since there would be not an uninstaller to clean up.

Another solution is to add an "Open test files" menu item that has the 'data' in the application folder as default.
This solution would not leave 'garbage' files in the user OS..

**Comment by giumas** [comment]
Given that one of the milestones proposes to unify the freezing mechanism to PyInstaller, I guess that the yesterday release is relevant: https://pypi.python.org/pypi/PyInstaller/3.0

**Comment by jreadey** [comment]
@giumas - thanks for the heads up about the new PyInstaller release.  I'll try it out today or tomorrow.

**Comment by jreadey** [comment]
Re: Sample Data files - I don't think this is worth the effort/increased complexity at this point.  We can include links to sample data files in the user guide.

**Comment by giumas** [comment]
> Re: Sample Data files - I don't think this is worth the effort/increased complexity at this point. We can include links to sample data files in the user guide.

I have just dropped that requirement from the initial list.

**Comment by giumas** [comment]
As described here: https://github.com/HDFGroup/hdf-compass/issues/63, I would drop the current 'in-house' `package_icons` mechanism and use `img2py`. To be honest, I would go farther.. and directly use the png and the icons (bundling them with PyInstaller).

**Comment by giumas** [comment]
There is also this minor thing on how `__init__.py` is currently abused: https://github.com/HDFGroup/hdf-compass/issues/67

**Comment by giumas** [comment]
This https://github.com/HDFGroup/hdf-compass/issues/69 would have high priority from my point of view. I need it to properly implement the BAG plugin.

**Comment by jreadey** [comment]
I'm closing this issue and switching to #79 as our plan of record for the next release.
