### ISSUE TITLE
Why do we have package_icons.py?

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#63]
I am not sure that I understand the reason of this module: https://github.com/HDFGroup/hdf-compass/blob/develop/package_icons.py

First, there is an `img2py` utility shipped with `wx` that provides the same functionalities (and more): the http://www.wxpython.org/docs/api/wx.tools.img2py-module.html

Then, why do we need to convert the images into a python modules when we can ship the original images? Both PyInstaller and py2app can bundle those files.

**Comment by jreadey** [comment]
@andrewcollette - is there a benefit to including the icons in pacakge_icons.py?

**Comment by andrewcollette** [comment]
I dimly recall img2py wasn't working on my system for some reason.  But I agree we should use standard tools.  Bundling the PNGs seems like a good approach.

**Comment by jreadey** [comment]
@giumas - would you be willing to do a PR that uses the img2py approach?

**Comment by giumas** [comment]
@jreadey : the bundling solution implies that we don't use `img2py`, but we directly read the png from the disk as I am doing here for the background logo: https://github.com/giumas/hdf-compass/blob/bag_ahead/hdf_compass/compass_viewer/frame.py#L281-L282 

This avoid the additional step to create the `image.py` to be imported. The disadvantage is that we need to bundle all the used png with the frozen application. This PR (https://github.com/HDFGroup/hdf-compass/pull/65) already does this for PyInstaller, with the helper function `collect_pkg_data`.

**Comment by giumas** [comment]
The current adopted solution is to use directly the figure files (not to create the images as importable modules as before)
