### ISSUE TITLE
Use (and abuse) of __init__.py

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#67]
Currently, all the various packages (`hdf5_model`, `compass_viewer`, etc.) have a lot of code (sometimes the whole implementation) in their `__init__.py`. 

This does not seem to be its proper use, since *"The \_\_init__.py files are required to make Python treat the directories as containing packages [...] In the simplest case, \_\_init__.py can just be an empty file, but it can also execute initialization code for the package or set the \_\_all__ variable, described later."* (https://docs.python.org/2/tutorial/modules.html#packages).

Just to cite some prominent examples on how the initiliazation module is used:

* `h5py`: https://github.com/h5py/h5py/blob/master/h5py/__init__.py
* `matplotlib`: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/delaunay/__init__.py
* `numpy`: https://github.com/numpy/numpy/blob/master/numpy/fft/__init__.py

Thus, the largest part of the code present in the `__init__.py` of a name package should be moved in a named module. For instance, we could add a `model.py` for all the packages that implement a plugin.

**Comment by jreadey** [comment]
@giumas - I'm hesitant to add this to the milestone list but will be happy to review and merge any pull requests related to this.

**Comment by giumas** [comment]
The above PRs implements the enhancement.
