### ISSUE TITLE
Extension of `compass_model` for text and xml

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#69]
Working on a format-specific plugin, I need to display some xml. There is not currently a `Node` class (`Store`, `Container`, `Array`, `Plottable`, and `Image`) well suited for this intent.

I propose to add:

* `class Text(Node)` with related viewer frame: `class TextFrame(NodeFrame)`
* `class Xml(Text)` with related viewer frame: `class XmlFrame(NodeFrame)`

**Comment by jreadey** [comment]
@giumas - this is an interesting idea that I could see would be useful for other plugins.

In using Compass with the hdf5_model, I frequently come across scalar attributes or datasets of string type where the view shows the grid with one cell which can't display much of the text.  So can imagine Text(Node) working well in that situation.

I imagine Json(Text) would be useful as well (but I don't think you are using JSON in BAG).

Can I assign this issue to you for inclusion in the next release?

**Comment by giumas** [comment]
@jreadey Yes, since I have to take care of it for the BAG plugin.

Another related enhancement would be to add a `plottable` property to the `Array` node to hide the "Plot" option in case like it is an array of characters. Right now with a dataset of ASCII string type we get: `ValueError: could not convert string to float: <`

**Comment by jreadey** [comment]
@giumas - yes, if it's just strings, it would be easy enough to check the dtype, but I can imagine other situations where you have numeric data but you'd want to hide the "Plot" option.

**Comment by jreadey** [comment]
See #94 for test case and description.

**Comment by giumas** [comment]
I close this after PR: https://github.com/HDFGroup/hdf-compass/pull/131

Base on the test case  https://github.com/HDFGroup/hdf-compass/issues/94 I got: 
![capture](https://cloud.githubusercontent.com/assets/2849257/10747591/8668927a-7c2d-11e5-8e99-c144d73c09a0.PNG)
