### ISSUE TITLE
Provide display of Plugins available

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf-compass#73]
Add info box displaying which plugins are available.

**Comment by jreadey** [comment]
On file open it wold be nice if there was a way the user could select which plugin to use (assuming multiple plugins support the given file).  Once (somewhat clunky) way to do this would be to have the "Show Plugin" dialog have enable/disable checkbox.

**Comment by giumas** [comment]
On my fork, by adding some logging debug message, I noticed that the local hdf5 files are open using the opendap model (when present). Is this the intended behavior?

**Comment by jreadey** [comment]
That's surprising - I'll take a look

**Comment by giumas** [comment]
If an url like "file://path/to/test.h5" can be handled by pydap.. why is this surprising? There will be multiple available handlers.. and just the 'last' one will be used. Thus, it becomes relevant what is the order of importing the modules. 

A different approach could be something like an ordered list of models with a 'priority' variable. For instance, with the BAG plugin, we may want to show the data with such a specific plugin rather than the generic HDF5 model. The current way to do this is based on the order of models import.

**Comment by jreadey** [comment]
I was thinking pydap only handled resources not local files.

Let's introduce a prefered extension(s) as part of the compass_model. E.g. the Bag plugin could list (*.bag) and a file with that extension would be loaded with the BAG plugin rather than the HDF5 plugin.

It would also be nice to have a "re-open as xyz" so users could look at the same file through another plugin (assuming it supported the file as well).

**Comment by giumas** [comment]
> On file open it wold be nice if there was a way the user could select which plugin to use (assuming multiple plugins support the given file).

I would split this ticket. The "Plugin info" box for this release, and a mechanism for disabling plugins for a future release: https://github.com/HDFGroup/hdf-compass/issues/132.

**Comment by giumas** [comment]
Something like this?

![capture](https://cloud.githubusercontent.com/assets/2849257/10901822/6e9103b2-81c3-11e5-8453-edb94ac5859f.PNG)

**Comment by jreadey** [comment]
That looks good.

**Comment by giumas** [comment]
Great! I will move forward by merging the PR. 

The plugin descriptions are currently minimal.. since I was just looking to have some text to visualize for each plugin. There is much more that can be added.

**Comment by jreadey** [comment]
Right, I'd expect plugins to provide a few sentences of description.  The description can always link to a url for more information.
