### ISSUE TITLE
Show attribute count in Group/Dataset/Datatype overview

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf-compass#74]
Display attribute count under Type description.

**Comment by giumas** [comment]
@jreadey Do you mean something like: "Attributes: N" where N is the number of available attributes? What about nested attributes?

**Comment by jreadey** [comment]
Correct.

What do you mean by nested attributes?  Attributes only exist as key value stores in Groups, Datasets, or Committed datatypes.  Attributes can't have attributes.

**Comment by giumas** [comment]
Sorry for the vagueness.. I mean, for instance, if we want to show in a container different icons for datasets with and without attributes.

**Comment by jreadey** [comment]
My preference would be to not bother with the different icon.

**Comment by jreadey** [comment]
added!
