### ISSUE TITLE
Issues with handling compound datatype files

### ISSUE THREAD

**Issue by kyang2014** [HDFGroup/hdf-compass#87]
1. File: ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/HDFCompass/kent-files/hdf5-handler-fake/comp_complex.h5

2.  Testing version: Windows version of the release candidate from S3

3. Issues about viewing the data:

Suggestions: use h5dump to dump the file to verify these issues. 
1). Datatype cmp1 treats an HDF5 Attributes, this is also discovered by JR at another ticket.

2). No information about compound datatype cmp1, cmp2,cmp3 can be found.
When opening the nested type, the Name, Value, Type,Shape are empty.

3). DIMENSION_LIST Attribute of  phony_compound_var 

The value and the Type don't make sense. 
  
[comp_complex_dimension_list_attributes.pdf](https://github.com/HDFGroup/hdf-compass/files/11974/comp_complex_dimension_list_attributes.pdf)

  The h5dump shows:
  ATTRIBUTE "DIMENSION_LIST" {
         DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): (DATASET 565 /n )
         }
      }

4) Missing data for phony_compound_var.

Only the first element of the member array is printed out.

[comp_complex_datavalues.docx](https://github.com/HDFGroup/hdf-compass/files/11976/comp_complex_datavalues.docx)

Note: 
 phony_compound_var[0].yy[1]((2,400000),......)  is missing.
phony_compound_var[1].yy[1]((4,800000),......)  is missing.
I think only the first element of the member (if the member is an array) is printed out.

The h5dump output: 
DATATYPE  H5T_COMPOUND {
         H5T_ARRAY { [2] H5T_COMPOUND {
            H5T_COMPOUND {
               H5T_STD_I16LE "i";
               H5T_STD_I32LE "j";
            } "x";
            H5T_ARRAY { [2] H5T_IEEE_F64LE } "y";
         } } "yy";
      }
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): {
            [ {
                  {
                     1,
                     200000
                  },
                  [ -100000, 3.14159 ]
               },
                {
                  {
                     2,
                     400000
                  },
                  [ 200000, 273.15 ]
               } ]
         },
      (1): {
            [ {
                  {
                     3,
                     600000
                  },
                  [ -200000, 6.14159 ]
               },
                {
                  {
                     4,
                     800000
                  },
                  [ 400000, 476.15 ]
               } ]
         }
      }
4. Issues with the plot
Two lines are plotted, which doesn’t make sense. In fact, I cannot make sense of any plot of a compound datatype. Can this be disabled?

**Comment by jreadey** [comment]
Test file available here: http://hdfgroup.s3.amazonaws.com/data/hdf5test/comp_complex.h5

**Comment by jreadey** [comment]
I can plot a field in a compound type by selecting the field and clicking Plot.  
Agree that plot should be disabled for compound types when no field is selected.
@kyang2014  - please create that as a separate feature request issue.
In general, let's aim for issues that identified one problem rather than several.  That way we can more easily address and resolve the issue.

I'll close this issue since I'm not sure there is anything else that has not been covered already.

**Comment by kyang2014** [comment]
How about this?

4) Missing data for phony_compound_var.

Only the first element of the member array is printed out.

comp_complex_datavalues.docx

Note: 
phony_compound_var[0].yy1 is missing.
phony_compound_var[1].yy1 is missing.
I think only the first element of the member (if the member is an array) is printed out.

**Comment by kyang2014** [comment]
About missing the second element of a field, I just found that if I click a field, I can see the full values. But the second element of a field is missing without clicking a field. Is this the right behavior?

If you look at a plot for any field, it all gives you the first sub field values,(0,1) to (1,3) and (0,2) to (2,4). This doesn't make sense. I will create another ticket.
