### ISSUE TITLE
Hard link information is not displayed 

### ISSUE THREAD

**Issue by kyang2014** [HDFGroup/hdf-compass#90]
1.  File: ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/HDFCompass/kent-files/hdf5-handler-fake/d_link_hard.h5

    Testing version: Windows version of the release candidate from S3

    Issues about viewing the data:
1) The hardlink of a group is not displayed. 

For example, GROUP "/g4"  is a   HARDLINK  of group "/g1/g3/g4_hard".  This is not displayed at compass.

2) The hardlink of a dataset is simple treated a duplicate dataset.

For example, /g2/dset1_hard is a hard link of datase /dset1. I can see two datasets that correctly have the same type,shape and values. It may be argued that the user should still know one dataset is a hardlink of another as the h5dump displays. 

H5dump output
```
h5dump d_link_hard.h5
HDF5 "d_link_hard.h5" {
GROUP "/" {
   DATASET "dset1" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SIMPLE { ( 5 ) / ( 5 ) }
      DATA {
      (0): 0, 1, 2, 3, 4
      }
   }
   GROUP "g1" {
      GROUP "g3" {
         DATASET "dset1_hard" {
            HARDLINK "/dset1"
         }
         GROUP "g4_hard" {
         }
      }
   }
   GROUP "g2" {
      DATASET "dset1_hard" {
         HARDLINK "/dset1"
      }
      GROUP "g4_hard" {
         HARDLINK "/g1/g3/g4_hard"
      }
   }
   GROUP "g4" {
      HARDLINK "/g1/g3/g4_hard"
   }
}
}
```

**Comment by jreadey** [comment]
I don't think it makes sense to say (for example) that "/dset" is the true path to the dataset, but /g2/dset_hard is a hardlink, so I would leave the behavior as is.

Feature request #26 would provide a better way to understand the structure of these types of files.

**Comment by kyang2014** [comment]
If you can make a graphic view like the request #26  that can distinguish all the links. But make sure all the original relations between different HDF5 objects should be preserved. 

For example, Yes, I agree that "it doesn't make sense to say (for example) that "/dset" is the true path to the dataset, but /g2/dset_hard is a hardlink. However, the current behavior treats /g2/dset_hard and /dset as two datasets, this doesn't Preserve the original meaning of an HDF5 file. You don't have to say one is another's hardlink. The relation between these objects two should be preserved.  Also How about the missing of the group hardlink info?
