### ISSUE TITLE
soft link information is not displayed for HDF5 group and is not displayed properly for HDF5 dataset

### ISSUE THREAD

**Issue by kyang2014** [HDFGroup/hdf-compass#91]
1.  File: ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/HDFCompass/kent-files/hdf5-handler-fake/d_link_soft.h5

    2. Testing version: Windows version of the release candidate from S3

   3. Issues about viewing the data:

1) The softlink of a group is not displayed.
For example, softlink /g2/slink4 is a softlink to the group /g1.  This is not present in some way at compass.

2) The softlink of a dataset is not displayed properly.
The softlink to an HDF5 dataset is treated the same as a hardlink of an HDF5 dataset. The linked HDF5 dataset shape, type and values are displayed but no information says this is a softlink to an HDF5 dataset. Two issues for this one: 1) The softlink information is not preserved. 2)A softlink is treated the same as a hardlink. This is not right. A softlink should be distinguished from a hardlink. 

h5dump output:
```
h5dump d_link_soft.h5
HDF5 "d_link_soft.h5" {
GROUP "/" {
   DATASET "dset1" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SIMPLE { ( 5 ) / ( 5 ) }
      DATA {
      (0): 0, 1, 2, 3, 4
      }
   }
   GROUP "g1" {
   }
   GROUP "g2" {
      SOFTLINK "slink3" {
         LINKTARGET "/dset1"
      }
      SOFTLINK "slink4" {
         LINKTARGET "/g1"
      }
   }
   SOFTLINK "slink1" {
      LINKTARGET "/dset1"
   }
   SOFTLINK "slink2" {
      LINKTARGET "/g1"
   }
}
}
```

**Comment by jreadey** [comment]
This is equivalent to #77.
