### ISSUE TITLE
HDF5 object reference values are not displayed properly

### ISSUE THREAD

**Issue by kyang2014** [HDFGroup/hdf-compass#92]
1. File: ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/HDFCompass/kent-files/hdf5-handler-fake/d_objref.h5

2. Testing version: Windows version of the release candidate from S3

3. Issues about viewing the data: The values of HDF5 object reference datasets are not displayed correctly.  I see all the values are <HDF5 object reference>.  The correct values can be found from h5dump output.

4. h5dump output
``` 
HDF5 "d_objref.h5" {
GROUP "/" {
   DATASET "DS1" {
      DATATYPE  H5T_REFERENCE { H5T_STD_REF_OBJECT }
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): GROUP 1400 /G1 , DATASET 800 /DS2
      }
   }
   DATASET "DS2" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SIMPLE { ( 5, 6 ) / ( 5, 6 ) }
      DATA {
      (0,0): 0, 1, 2, 3, 4, 5,
      (1,0): 1, 2, 3, 4, 5, 6,
      (2,0): 2, 3, 4, 5, 6, 7,
      (3,0): 3, 4, 5, 6, 7, 8,
      (4,0): 4, 5, 6, 7, 8, 9
      }
   }
   GROUP "G1" {
   }
}
}
```

**Comment by kyang2014** [comment]
I miss some information for writing the issue. Repeat the issue:

The values of HDF5 object reference datasets are not displayed correctly.
 I see all the values are <HDF5 object reference>. The correct values can be found from h5dump output.

**Comment by kyang2014** [comment]
Strangely, github removes some of my writing when I push the comment.  Try again with another browser. 

The wrong object reference values displayed at compass are "HDF5 object references". The correct values can be found from the h5dump output.

**Comment by jreadey** [comment]
I'm putting this in the enhancement category.

**Comment by jreadey** [comment]
Closing this and using #102 to track type related issues.
