### ISSUE TITLE
HDF5 region reference values are not displayed properly 

### ISSUE THREAD

**Issue by kyang2014** [HDFGroup/hdf-compass#93]
1. File: ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/HDFCompass/kent-files/hdf5-handler-fake/d_regref.h5

2. Testing version: Windows version of the release candidate from S3

The values of HDF5 region reference datasets are not displayed correctly. I see all the values are "HDF5 region references". The correct values can be found from h5dump output. It looks like:
```
DATASET "DS1" {
      DATATYPE  H5T_REFERENCE { H5T_STD_REF_DSETREG }
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
         DATASET /DS2 {(0,1), (2,11), (1,0), (2,4)},
         DATASET /DS2 {(0,0)-(0,2), (0,11)-(0,13), (2,0)-(2,2), (2,11)-(2,13)}
      }
   }
```

**Comment by jreadey** [comment]
Closing this and using #102 to track type enhancements.
