### ISSUE TITLE
Various HDF5 datatypes displayed as "Unknown" datatypes 

### ISSUE THREAD

**Issue by kyang2014** [HDFGroup/hdf-compass#95]
1) File: ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/HDFCompass/kent-files/hdf5-handler-fake/ntypes.h5

2) Testing version: Windows version of the release candidate from S3

Potential bug: I found variable length string (vlstr_type) is marked as "Type Unknown", this is not right.

The rest "Type Unknown" perhaps more or less a documentation issue. However, the compass experts should carefully review these.

The following HDF5 datatypes are  also marked as "Type Unknown" 
1) HDF5 region reference  (Dataset1)
2) HDF5 object reference (Dataset3)
3) HDF5 array datatype (array_type)
4) HDF5 bitfield (bitfield_type_1)
5) HDF5 opaque type(opaque_type)
6) HDF5 variable length type(vl_type)

In addition,
7) HDF5 ENUM type(enum_type) is marked as 2-byte signed integer(which essentially is right)

**Comment by jreadey** [comment]
Closing this and using #102 to track.
