### ISSUE TITLE
HDF5 Opaque type values don't show up 

### ISSUE THREAD

**Issue by kyang2014** [HDFGroup/hdf-compass#98]
1) File: ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/HDFCompass/kent-files/hdf5-handler-fake/ntypes.h5

2) Testing version: Windows version of the release candidate from S3

HDF5 opaque type(opaque_type) dataset values don't show up. The Value table show up with empty cells. I think this may be a document issue or error handling. I prefer  to see a message like : unsupported datatype, values may not show up or may not be right,  

The opaque tag is also not presented as h5dump does.
h5dump output:

DATASET "opaque_type" {
      DATATYPE  H5T_OPAQUE {
         OPAQUE_TAG "testing 1-byte opaque type";
      }
      DATASPACE  SIMPLE { ( 32 ) / ( 32 ) }
      DATA {
      (0): 0xff, 0xfe, 0xfd, 0xfc, 0xfb, 0xfa, 0xf9, 0xf8, 0xf7, 0xf6, 0xf5,
      (11): 0xf4, 0xf3, 0xf2, 0xf1, 0xf0, 0xef, 0xee, 0xed, 0xec, 0xeb, 0xea,
      (22): 0xe9, 0xe8, 0xe7, 0xe6, 0xe5, 0xe4, 0xe3, 0xe2, 0xe1, 0xe0
      }

**Comment by jreadey** [comment]
@kyang2014 - is that the correct data file?  I don't see any opaque types.

**Comment by kyang2014** [comment]
My mistake, corrected the file name.

**Comment by jreadey** [comment]
Closing this and using #102 to track.
